"""FlowState v2 validation: metrics, wave detection, string stability,
FHWA-style acceptance criteria, the corridor study protocol's bottleneck check
and baseline gate (docs/FRISCO_PROTOCOL.md §§5-6), and the auto-generated
validation report (CLAUDE.md §7; docs/CONTRACTS.md §§3, 4, 7)."""

from validation.baseline_gate import (
    CheckResult,
    DaySetScore,
    GateResult,
    evaluate_gate,
    gate_from_replicates,
    rescore,
    score_day_set,
)
from validation.bottlenecks import (
    Bottleneck,
    BottleneckComparison,
    compare_bottlenecks,
    identify_bottlenecks,
)
from validation.criteria import (
    CRITERIA_PROFILES,
    CriteriaProfile,
    CriteriaResult,
    evaluate,
    get_profile,
)
from validation.fields import (
    DensityField,
    FlowField,
    SpeedField,
    density_field,
    flow_field,
    speed_field,
)
from validation.metrics import (
    CI,
    LinkHourGEH,
    Metrics,
    aggregate,
    ci,
    compute_metrics,
    count_crossings,
    crossings_per_window,
    default_travel_span,
    geh,
    geh_pass_fraction,
    link_hour_geh,
    rmspe,
    travel_times,
    warmup_from_meta,
)
from validation.observed import (
    LinkHourRecord,
    ObservedCorridor,
    ObservedCoverage,
    ObservedProvenance,
    ObservedScores,
    ObservedStation,
    PooledLinkHour,
    clock_label,
    no_comparison_provenance,
    pool_link_hours,
    pool_scores,
    score_run_against_observed,
)
from validation.report import ReportRefusedError, generate_report
from validation.ring_benchmark import evaluate_ring_benchmark
from validation.string_stability import (
    IDMPartials,
    equilibrium_gap,
    equilibrium_speed,
    idm_partials,
    is_string_stable,
    stability_criterion,
    unstable_band,
)
from validation.waves import (
    WAVE_DETECTORS,
    Wave,
    WaveDetector,
    WaveMeasurement,
    WaveSet,
    detect_waves,
    get_detector,
    planted_stripe_field,
    stack_wave_speed,
)

__all__ = [
    "CI",
    "CRITERIA_PROFILES",
    "WAVE_DETECTORS",
    "Bottleneck",
    "BottleneckComparison",
    "CheckResult",
    "CriteriaProfile",
    "CriteriaResult",
    "DaySetScore",
    "DensityField",
    "FlowField",
    "GateResult",
    "IDMPartials",
    "LinkHourGEH",
    "LinkHourRecord",
    "Metrics",
    "ObservedCorridor",
    "ObservedCoverage",
    "ObservedProvenance",
    "ObservedScores",
    "ObservedStation",
    "PooledLinkHour",
    "ReportRefusedError",
    "SpeedField",
    "Wave",
    "WaveDetector",
    "WaveMeasurement",
    "WaveSet",
    "aggregate",
    "ci",
    "clock_label",
    "compare_bottlenecks",
    "compute_metrics",
    "count_crossings",
    "crossings_per_window",
    "default_travel_span",
    "density_field",
    "detect_waves",
    "equilibrium_gap",
    "equilibrium_speed",
    "evaluate",
    "evaluate_gate",
    "evaluate_ring_benchmark",
    "flow_field",
    "gate_from_replicates",
    "geh",
    "geh_pass_fraction",
    "generate_report",
    "get_detector",
    "get_profile",
    "identify_bottlenecks",
    "idm_partials",
    "is_string_stable",
    "link_hour_geh",
    "no_comparison_provenance",
    "planted_stripe_field",
    "pool_link_hours",
    "pool_scores",
    "rescore",
    "rmspe",
    "score_day_set",
    "score_run_against_observed",
    "speed_field",
    "stability_criterion",
    "stack_wave_speed",
    "travel_times",
    "unstable_band",
    "warmup_from_meta",
]
