"""FlowState v2 validation: metrics, wave detection, string stability,
FHWA-style acceptance criteria, and the auto-generated validation report
(CLAUDE.md §7; docs/CONTRACTS.md §§3, 4, 7)."""

from validation.criteria import (
    CRITERIA_PROFILES,
    CriteriaProfile,
    CriteriaResult,
    evaluate,
    get_profile,
)
from validation.fields import (
    DensityField,
    FlowField,
    SpeedField,
    density_field,
    flow_field,
    speed_field,
)
from validation.metrics import (
    CI,
    LinkHourGEH,
    Metrics,
    aggregate,
    compute_metrics,
    count_crossings,
    crossings_per_window,
    geh,
    geh_pass_fraction,
    link_hour_geh,
    rmspe,
    travel_times,
)
from validation.report import ReportRefusedError, generate_report
from validation.ring_benchmark import evaluate_ring_benchmark
from validation.string_stability import (
    IDMPartials,
    equilibrium_gap,
    equilibrium_speed,
    idm_partials,
    is_string_stable,
    stability_criterion,
    unstable_band,
)
from validation.waves import (
    WAVE_DETECTORS,
    Wave,
    WaveDetector,
    WaveMeasurement,
    WaveSet,
    detect_waves,
    get_detector,
    planted_stripe_field,
    stack_wave_speed,
)

__all__ = [
    "CI",
    "CRITERIA_PROFILES",
    "WAVE_DETECTORS",
    "CriteriaProfile",
    "CriteriaResult",
    "DensityField",
    "FlowField",
    "IDMPartials",
    "LinkHourGEH",
    "Metrics",
    "ReportRefusedError",
    "SpeedField",
    "Wave",
    "WaveDetector",
    "WaveMeasurement",
    "WaveSet",
    "aggregate",
    "compute_metrics",
    "count_crossings",
    "crossings_per_window",
    "density_field",
    "detect_waves",
    "equilibrium_gap",
    "equilibrium_speed",
    "evaluate",
    "evaluate_ring_benchmark",
    "flow_field",
    "geh",
    "geh_pass_fraction",
    "generate_report",
    "get_detector",
    "get_profile",
    "idm_partials",
    "is_string_stable",
    "link_hour_geh",
    "planted_stripe_field",
    "rmspe",
    "speed_field",
    "stability_criterion",
    "stack_wave_speed",
    "travel_times",
    "unstable_band",
]
