"""Acceptance criteria (CLAUDE.md §7.1) as data, not prose.

Encodes acceptance tables as :class:`CriteriaProfile` records held in the
:data:`CRITERIA_PROFILES` registry (``get_profile(name)``) and evaluates
supplied measurements into honest pass/fail rows — no rounding games; a
missing input is reported as *not evaluated and failing* (CLAUDE.md §0.1).

Every profile carries a ``source`` string stating exactly which document,
section and table its numbers were transcribed from, what was verified in
this repository's session and how, and which fields are FlowState's own
conventions rather than the document's. Read those strings before quoting a
profile in a report. Summary of the verification (2026-09-03):

* **FHWA Traffic Analysis Toolbox Vol. III, 2004** (FHWA-HRT-04-040), §5.6
  "Calibration Targets", verified on the HTML edition at
  https://ops.fhwa.dot.gov/trafficanalysistools/tat_vol3/sect5.htm, where the
  Wisconsin DOT freeway calibration table is captioned "Table 4" (attributed
  to WisDOT District 2, Paramics Calibration and Validation Guidelines,
  Technical Report I-33, June 2002). Rows: individual link flows within 15%
  (700–2,700 veh/h), within 100 veh/h (< 700), within 400 veh/h (> 2,700),
  each for > 85% of cases; sum of all link flows within 5%; **GEH < 5 for
  individual link flows in > 85% of cases**; GEH < 4 for the sum; journey
  times within 15% (or 1 min if higher) for > 85% of cases; visual audits to
  the analyst's satisfaction. CLAUDE.md §7.1 refers to this as "Table 5";
  the HTML edition numbers it Table 4 — the PDF numbering was not checked.
* **FHWA Traffic Analysis Toolbox Vol. III, 2019 update** (FHWA-HOP-18-036),
  Chapter 5 "Model Calibration", verified at
  https://ops.fhwa.dot.gov/publications/fhwahop18036/chapter5.htm: it
  contains **no GEH or 85% target**. It derives project-specific acceptance
  envelopes from observed-data variability (Criteria I–IV: 95% of simulated
  outputs inside the time-variant envelope; two-thirds inside the
  representative-day band; bounded dynamic absolute and systematic error)
  and states "The analyst does not need to calibrate multiple model runs
  generated by varying the random number seeds." The fixed GEH/85% wording
  that CLAUDE.md attributes to "FHWA-HOP-18-036 usage" is therefore the
  2004 edition's (and its DOT descendants'), not the 2019 text.
* **Oregon DOT, Protocol for VISSIM Simulation (June 2011)**, read from the
  PDF at https://www.oregon.gov/odot/Planning/Documents/APMv2_Add15A.pdf,
  §6.1 Tables 6-1/6-2, §6.2, §6.3 Table 6-3, §6.9.
* **TxDOT Traffic and Safety Analysis Procedures Manual, Chapter 13
  "Microsimulation Analysis"**, §13.5.2 "Acceptability Criteria" and
  §13.5.2.3 "Throughput", read at
  https://www.txdot.gov/manuals/des/tsp/chapter-13-microsimulation-analysis/13-5-calibration/13-5-2-acceptability-criteria.html
  (Tables 13-4 and 13-5). The travel-time criteria of §13.5.2.2 (Table
  13-3) are equations published as images and could not be read.

The segment-speed RMSPE bound, the emergent backward wave-speed band, the
ring benchmarks, the ≥ 20-seed rule and the penetration × compliance grid are
FlowState requirements from CLAUDE.md §7.1/§0.6, present in every profile and
labeled as such in ``source``; no DOT document above prescribes them.

**Model integrity: no SUMO collisions** (2026-10-04, owner decision, WP-98).
Every profile's results end with a ``no_collisions`` row, evaluated from the
per-run collision counts (``meta.json["n_collisions"]``, read by
``validation.battery.collision_count``): PASS only when every run records the
counter and the total is zero; FAIL when any run records a collision; NOT
RECORDED — never a pass, never a zero — when no failure is recorded but some
run lacks the counter or no counts were supplied (:func:`zero_collisions`).
A collision in a car-following simulation is a model defect, not a traffic
outcome (CLAUDE.md §3.3: controllers must not be able to command
collisions). It is a FlowState internal standard, not an FHWA or DOT
criterion, and its row says so. A NOT RECORDED row has ``evaluated=False``
and a ``detail`` starting with :data:`NOT_RECORDED`; :attr:`CriteriaResult.
status` names the four outcomes.

**Model integrity: no locks** (2026-10-07, docs/I94_COLLAPSE_DIAGNOSIS.md
§7). Every profile's results end, after ``no_collisions``, with a
``no_locks`` row, evaluated from the per-run lock records of
:mod:`validation.locks` (``RunLocks.locked``: True when vehicles stood with
no discharge past a point for at least
:data:`validation.locks.LOCK_MIN_DURATION_S` with a queue behind it):
PASS only when every run is recorded and none locked; FAIL when any run
locked; NOT RECORDED when no run locked but some run carries neither file the
detector reads (``edges.parquet``, ``vehicles.parquet``) or no records were
supplied (:func:`zero_locks`). A permanent standstill in a simulation without
teleporting is a model defect (no release rule reaches the vehicle at its
front), not a traffic outcome; every metric of a locked run includes the
vehicles trapped behind it. It is a FlowState internal standard, not an FHWA
or DOT criterion, and its row says so.

The wave-speed row's number depends on the detector that produced it, so
every profile names its detector (``wave_detector``, a
:class:`validation.waves.WaveDetector`) and the evaluated row records that
recipe in its ``detail``. The default is ``stack``: on the planted-stripe
benchmark of ``validation.waves`` it is the only registered detector that
recovers the planted speed at every congested fraction from 0.3 to 0.95
(16.0–16.1 km/h for 16 planted) — the ``standard`` 40 km/h detector finds no
backward front at any of them because a congested background is one
component whose front is the standing queue tail, ``relative`` finds none
below 90% congestion, and ``stripe`` is biased by up to 4.4 km/h when the
background sits near its own 25 km/h threshold. Callers state the detector
they used via ``evaluate(..., wave_detector=...)``; a value measured with a
different recipe is reported as not evaluated rather than scored.
"""

from __future__ import annotations

import math
from collections.abc import Sequence
from dataclasses import dataclass, field
from typing import Final, Literal

from flowstate_core.constants import WAVE_SPEED_BAND_KMH
from validation.locks import LOCK_MIN_DURATION_S
from validation.waves import STACK_DETECTOR, WaveDetector

#: Penetrations of the CLAUDE.md §7.1 sensitivity grid (fractions).
REQUIRED_PENETRATIONS: tuple[float, ...] = (0.01, 0.02, 0.05, 0.10, 0.15, 0.20)
#: Compliances of the CLAUDE.md §7.1 sensitivity grid (fractions).
REQUIRED_COMPLIANCES: tuple[float, ...] = (0.25, 0.5, 0.8, 1.0)

#: Name of the model-integrity row every profile's results carry.
NO_COLLISIONS: Final[str] = "no_collisions"
#: ``detail`` prefix of a row whose input some run did not record: the row is
#: neither a pass nor a zero (``CriteriaResult.status`` reads "NOT RECORDED").
NOT_RECORDED: Final[str] = "not recorded"
#: Provenance of the ``no_collisions`` row, written into its ``detail``.
NO_COLLISIONS_STANDARD: Final[str] = (
    "FlowState internal standard (CLAUDE.md §3.3; owner decision 2026-10-04), "
    "not an FHWA or DOT criterion"
)
#: Name of the second model-integrity row every profile's results carry.
NO_LOCKS: Final[str] = "no_locks"
#: Provenance of the ``no_locks`` row, written into its ``detail``.
NO_LOCKS_STANDARD: Final[str] = (
    "FlowState internal standard (CLAUDE.md §0.1; docs/I94_COLLAPSE_DIAGNOSIS.md §7, "
    "2026-10-07), not an FHWA or DOT criterion"
)
#: Seconds per minute (the ``no_locks`` threshold is stated in minutes).
_S_PER_MIN: Final[float] = 60.0

#: The outcome of one row: PASS / FAIL when evaluated; NOT RECORDED when an
#: input some run should have recorded is missing; NOT EVALUATED otherwise.
CriterionStatus = Literal["PASS", "FAIL", "NOT EVALUATED", "NOT RECORDED"]

_FLOWSTATE_ROWS = (
    "The segment-speed RMSPE <= 15% bound is FlowState's own convention "
    "(CLAUDE.md §7.1, 'common microsim practice'); the 14-22 km/h emergent "
    "backward wave-speed band is the empirical stop-and-go literature value "
    "(flowstate_core.constants.WAVE_SPEED_BAND_KMH); the ring emergence/dampening "
    "rows reproduce Sugiyama et al. (2008) and Stern et al. (2018) per CLAUDE.md "
    "§3.2.1; min_seeds = 20 and the penetration {1,2,5,10,15,20}% x compliance "
    "{25,50,80,100}% grid are CLAUDE.md §0.6/§7.1 internal standards; so is the "
    "no_collisions model-integrity row (zero SUMO collisions in every run, each run "
    "recording the counter; CLAUDE.md §3.3 and the owner decision of 2026-10-04) and "
    "the no_locks row (no run locked: no queue standing without discharge for the "
    "validation.locks duration; docs/I94_COLLAPSE_DIAGNOSIS.md, 2026-10-07), both "
    "present in every profile. None of "
    "these is prescribed by the cited DOT/FHWA documents. The wave-speed row is "
    "measured with the profile's wave_detector (validation.waves.WAVE_DETECTORS; "
    "default 'stack', chosen on the planted-stripe benchmark in validation.waves), "
    "and the evaluated row names that detector and its parameters."
)

FHWA_DEFAULT_SOURCE = (
    "FlowState default profile (CLAUDE.md §7.1). GEH < 5 for >= 85% of link-hour "
    "comparisons transcribes the 'GEH Statistic < 5 for Individual Link Flows: "
    "> 85% of cases' row of the Wisconsin DOT freeway model calibration criteria "
    "table (captioned 'Table 4' on the HTML edition) in §5.6 'Calibration Targets' "
    "of the FHWA Traffic Analysis Toolbox Vol. III, 2004 (FHWA-HRT-04-040), verified "
    "2026-09-03 at https://ops.fhwa.dot.gov/trafficanalysistools/tat_vol3/sect5.htm; "
    "the source says '> 85%' where this profile, like CLAUDE.md, uses '>= 85%' "
    "(geh_pass_inclusive=True). The 2019 update (FHWA-HOP-18-036) Chapter 5, "
    "verified the same day at https://ops.fhwa.dot.gov/publications/fhwahop18036/chapter5.htm, "
    "prescribes no GEH or 85% target (it builds data-driven variation envelopes, "
    "Criteria I-IV) and says the analyst need not calibrate multiple random-seed "
    "runs; the citation of FHWA-HOP-18-036 for the GEH wording elsewhere in this "
    "repository is therefore a citation of the toolbox lineage, not of the 2019 "
    "text. " + _FLOWSTATE_ROWS
)

FHWA_TAT3_2004_SOURCE = (
    "FHWA Traffic Analysis Toolbox Vol. III (2004, FHWA-HRT-04-040), §5.6 "
    "'Calibration Targets', Wisconsin DOT freeway model calibration criteria "
    "(captioned 'Table 4' on the HTML edition at "
    "https://ops.fhwa.dot.gov/trafficanalysistools/tat_vol3/sect5.htm, verified "
    "2026-09-03; attributed there to WisDOT District 2, Paramics Calibration and "
    "Validation Guidelines, Technical Report I-33, June 2002). Transcribed row: "
    "'GEH Statistic < 5 for Individual Link Flows: > 85% of cases' — strict "
    "'> 85%' (geh_pass_inclusive=False). Rows of that table NOT evaluated by "
    "FlowState: individual link flows within 15% / 100 veh/h / 400 veh/h by flow "
    "band for > 85% of cases; sum of all link flows within 5%; GEH < 4 for the sum "
    "of all link flows; journey times within 15% (or 1 min, if higher) for > 85% "
    "of cases; visual audits of speed-flow relationships and bottleneck queuing "
    "'to analyst's satisfaction'. The table defines no RMSPE speed bound, so this "
    "profile produces no speeds_rmspe row (rmspe_max=None). The 2004 volume gives "
    "no fixed minimum run count (its §5 example uses ten replications to estimate "
    "a parameter within 5%), so min_seeds keeps FlowState's 20 (CLAUDE.md §0.6). " + _FLOWSTATE_ROWS
)

ODOT_VISSIM_2011_SOURCE = (
    "Oregon DOT, 'Protocol for VISSIM Simulation' (June 2011), read 2026-09-03 "
    "from the PDF at https://www.oregon.gov/odot/Planning/Documents/APMv2_Add15A.pdf. "
    "§6.1 'Volume/Density', Table 6-2 'Traffic Volume Calibration Criteria': "
    "'GEH < 5.0 — At least 85% of freeway links within the calibration area' "
    "(transcribed: geh_threshold=5.0, geh_pass_fraction=0.85, inclusive). Rows of "
    "Table 6-2 NOT evaluated by FlowState: GEH < 5.0 for all entry and exit "
    "locations, all entrance and exit ramps, and all intersection turn movements "
    "> 100 veh/h; individual flows within +/-400 veh/h for flows exceeding 2,700 "
    "veh/h on at least 85% of applicable mainline links; sum of all link flows "
    "within 5%. Table 6-1 'GEH Statistic Guidelines': GEH < 5.0 acceptable fit; "
    "5.0 <= GEH <= 10.0 caution (possible model error or bad data); GEH > 10.0 "
    "unacceptable. §6.9 'Minimum Number of Simulation Runs': 'All model results "
    "reported shall be an average of a minimum of 10 simulation runs with "
    "different random number seeds' (transcribed: min_seeds=10; FlowState's own "
    "20-seed headline rule, CLAUDE.md §0.6, still drives the underpowered flag of "
    "validation.metrics.aggregate). §6.2 'Speed': spot speeds within 10 percent "
    "of observed at key calibration locations and, where network-wide data exist, "
    "within 10 mph on at least 85 percent of freeway links — a per-location "
    "tolerance, not an RMSPE, so this profile defines no RMSPE bound and produces "
    "no speeds_rmspe row (rmspe_max=None). §6.3 Table 6-3 'Travel Time Calibration "
    "Criteria' (+/-1 min for routes under 7 min, +/-15% over 7 min; attributed to "
    "FHWA TAT Vol. III / Wisconsin DOT) is not evaluated by FlowState. " + _FLOWSTATE_ROWS
)

TXDOT_TSAP_CH13_SOURCE = (
    "TxDOT Traffic and Safety Analysis Procedures Manual, Chapter 13 "
    "'Microsimulation Analysis', §13.5.2 'Acceptability Criteria' and §13.5.2.3 "
    "'Throughput', read 2026-09-03 at https://www.txdot.gov/manuals/des/tsp/"
    "chapter-13-microsimulation-analysis/13-5-calibration/13-5-2-acceptability-criteria.html "
    "(no revision date shown). Table 13-4 'GEH Statistic Guidelines': < 3.0 "
    "acceptable fit; 3.0 to 5.0 acceptable for local roadway facilities; > 5.0 "
    "unacceptable. Table 13-5 'Throughput Calibration Targets': GEH < 3.0 for all "
    "state facility segments, all entry/exit points and all ramps; GEH < 5.0 for "
    "at least 85% of local roadway segments; sum of all segment flows within 5%. "
    "This profile transcribes the state-facility row, the applicable one for a "
    "freeway corridor: geh_threshold=3.0 on every comparison "
    "(geh_pass_fraction=1.0); the local-roadway row would be 5.0 for >= 85%. The "
    "manual states 'For all FHWA related projects, it is necessary to use the "
    "FHWA 2019 Guidelines. For non-FHWA projects, calibration criteria is "
    "typically determined during project scoping and based on discussions with "
    "the TxDOT project manager.' NOT transcribed: the travel-time criteria of "
    "§13.5.2.2 Table 13-3 (free-flowing and interrupted-flow tolerance equations "
    "published as images, unreadable in the session); the sum-of-flows row; any "
    "minimum run count (not located on the pages consulted, so min_seeds keeps "
    "FlowState's 20, CLAUDE.md §0.6). The manual defines no RMSPE speed bound, so "
    "no speeds_rmspe row is produced (rmspe_max=None). " + _FLOWSTATE_ROWS
)


@dataclass(frozen=True)
class CriteriaProfile:
    """One named set of acceptance thresholds (CLAUDE.md §7.1 table).

    The defaults reproduce the ``fhwa_default`` profile, so
    ``CriteriaProfile()`` is that profile.

    Attributes:
        name: Profile identifier (recorded in reports).
        source: Provenance: document, section, table, what was verified and
            how, and which fields are FlowState conventions. Never empty.
        geh_threshold: Per-comparison GEH acceptance bound (strict ``<``).
        geh_pass_fraction: Minimum fraction of link-hour comparisons that
            must satisfy the GEH bound.
        geh_pass_inclusive: Whether the fraction test is ``>=`` (True) or
            strict ``>`` (False, the 2004 FHWA table's "> 85% of cases").
        rmspe_max: Maximum segment-speed RMSPE as a fraction (inclusive), or
            ``None`` when the profile's source defines no RMSPE bound — the
            ``speeds_rmspe`` row is then not produced.
        wave_speed_band_kmh: Acceptance band for the emergent backward
            wave-front speed magnitude [km/h], inclusive on both ends.
        wave_detector: The :class:`validation.waves.WaveDetector` recipe
            that must produce ``wave_speed_kmh`` for this profile; its
            description is written into the evaluated row. Default
            ``validation.waves.STACK_DETECTOR`` — see the module docstring
            for the benchmark evidence. ``validation.report.generate_report``
            measures the criterion with this detector, on fields binned at
            this detector's own bins, and states it to :func:`evaluate`; the
            ``wave_speed_kmh`` of ``validation.metrics.compute_metrics`` is a
            separate ``standard``-detector diagnostic that appears in the
            report's metric tables and is never scored as this row.
        min_seeds: Minimum replicate count for headline reporting.
        require_ring_emergence: Include the Sugiyama ring emergence check.
        require_ring_dampening: Include the Stern single-AV dampening check.
        require_sensitivity_grid: Include the penetration × compliance grid
            check (CLAUDE.md §7.1 "Sensitivity" row).
        required_penetrations: Penetration levels the grid must contain.
        required_compliances: Compliance levels the grid must contain.
    """

    name: str = "fhwa_default"
    source: str = FHWA_DEFAULT_SOURCE
    geh_threshold: float = 5.0
    geh_pass_fraction: float = 0.85
    geh_pass_inclusive: bool = True
    rmspe_max: float | None = 0.15
    wave_speed_band_kmh: tuple[float, float] = field(default=WAVE_SPEED_BAND_KMH)
    wave_detector: WaveDetector = STACK_DETECTOR
    min_seeds: int = 20
    require_ring_emergence: bool = True
    require_ring_dampening: bool = True
    require_sensitivity_grid: bool = True
    required_penetrations: tuple[float, ...] = REQUIRED_PENETRATIONS
    required_compliances: tuple[float, ...] = REQUIRED_COMPLIANCES

    def __post_init__(self) -> None:
        if not self.source.strip():
            raise ValueError(f"profile {self.name!r} needs a non-empty source")
        if not 0.0 < self.geh_pass_fraction <= 1.0:
            raise ValueError(f"geh_pass_fraction must be in (0, 1], got {self.geh_pass_fraction}")


FHWA_DEFAULT = CriteriaProfile()

FHWA_TAT3_2004 = CriteriaProfile(
    name="fhwa_tat3_2004",
    source=FHWA_TAT3_2004_SOURCE,
    geh_threshold=5.0,
    geh_pass_fraction=0.85,
    geh_pass_inclusive=False,
    rmspe_max=None,
)

ODOT_VISSIM_2011 = CriteriaProfile(
    name="odot_vissim_2011",
    source=ODOT_VISSIM_2011_SOURCE,
    geh_threshold=5.0,
    geh_pass_fraction=0.85,
    geh_pass_inclusive=True,
    rmspe_max=None,
    min_seeds=10,
)

TXDOT_TSAP_CH13 = CriteriaProfile(
    name="txdot_tsap_ch13",
    source=TXDOT_TSAP_CH13_SOURCE,
    geh_threshold=3.0,
    geh_pass_fraction=1.0,
    geh_pass_inclusive=True,
    rmspe_max=None,
)

CRITERIA_PROFILES: dict[str, CriteriaProfile] = {
    p.name: p for p in (FHWA_DEFAULT, FHWA_TAT3_2004, ODOT_VISSIM_2011, TXDOT_TSAP_CH13)
}
"""Selectable profiles by name (CLAUDE.md §7.1: state-DOT variants)."""


def get_profile(name: str) -> CriteriaProfile:
    """Look up a registered :class:`CriteriaProfile` by name.

    Args:
        name: Key of :data:`CRITERIA_PROFILES`.

    Returns:
        The profile.

    Raises:
        KeyError: Unknown name; the message lists the available profiles.
    """
    try:
        return CRITERIA_PROFILES[name]
    except KeyError as exc:
        raise KeyError(
            f"unknown criteria profile {name!r}; available: {sorted(CRITERIA_PROFILES)}"
        ) from exc


@dataclass(frozen=True)
class CriteriaResult:
    """One evaluated acceptance-criterion row.

    Attributes:
        name: Criterion identifier.
        value: Measured value, or ``None`` when the input was not supplied.
        threshold: Human-readable threshold description.
        passed: Honest pass/fail; always ``False`` when not evaluated.
        evaluated: Whether a usable input was available to evaluate (a
            wave speed measured with a detector other than the profile's
            is present but not usable).
        detail: Optional explanatory note; for ``wave_speed`` it names the
            detector recipe behind the value. A row whose input some run did
            not record starts it with :data:`NOT_RECORDED`.
    """

    name: str
    value: float | None
    threshold: str
    passed: bool
    evaluated: bool
    detail: str = ""

    @property
    def status(self) -> CriterionStatus:
        """``PASS`` / ``FAIL`` when evaluated, else ``NOT RECORDED`` (the
        ``detail`` starts with :data:`NOT_RECORDED`) or ``NOT EVALUATED``.
        Neither of the last two is a pass."""
        if self.evaluated:
            return "PASS" if self.passed else "FAIL"
        return "NOT RECORDED" if self.detail.startswith(NOT_RECORDED) else "NOT EVALUATED"


def zero_collisions(counts: Sequence[int | None]) -> bool | None:
    """Whether a run set is collision-free, from its per-run collision counts.

    Args:
        counts: One entry per run: its ``meta.json["n_collisions"]``, or None
            when the run does not record the counter
            (``validation.battery.collision_count``).

    Returns:
        False when any run records a collision (whatever the others record);
        otherwise None when the set is empty or any run lacks the counter (not
        recorded is not zero); True only when every run records zero.
    """
    recorded = [c for c in counts if c is not None]
    if any(c > 0 for c in recorded):
        return False
    if not counts or len(recorded) < len(counts):
        return None
    return True


def _collision_row(counts: Sequence[int | None] | None) -> CriteriaResult:
    """The ``no_collisions`` row (module docstring, "Model integrity").

    Args:
        counts: Per-run collision counts (None for a run without the
            counter), or None when the caller supplied none.

    Returns:
        The row: FAIL (``value`` the total over the runs that record it),
        PASS (``value`` 0) or NOT RECORDED (``value`` None).
    """
    text = "zero SUMO collisions in every run, each run recording the counter"
    if counts is None:
        return CriteriaResult(
            name=NO_COLLISIONS,
            value=None,
            threshold=text,
            passed=False,
            evaluated=False,
            detail=f"{NOT_RECORDED}: no per-run collision counts supplied; "
            + NO_COLLISIONS_STANDARD,
        )
    recorded = [c for c in counts if c is not None]
    n_missing = len(counts) - len(recorded)
    total = sum(recorded)
    flag = zero_collisions(counts)
    if flag is None:
        why = (
            "no runs supplied"
            if not counts
            else f"{n_missing} of {len(counts)} run(s) carry no collision counter "
            "(meta.json n_collisions)"
        )
        return CriteriaResult(
            name=NO_COLLISIONS,
            value=None,
            threshold=text,
            passed=False,
            evaluated=False,
            detail=f"{NOT_RECORDED}: {why}; {NO_COLLISIONS_STANDARD}",
        )
    if flag:
        detail = f"no collision in {len(counts)} run(s); {NO_COLLISIONS_STANDARD}"
    else:
        n_with = sum(1 for c in recorded if c > 0)
        detail = (
            f"{total} collision(s) in {n_with} of {len(recorded)} run(s) that record the counter"
            + (f"; {n_missing} run(s) not recorded" if n_missing else "")
            + f"; {NO_COLLISIONS_STANDARD}"
        )
    return CriteriaResult(
        name=NO_COLLISIONS,
        value=float(total),
        threshold=text,
        passed=flag,
        evaluated=True,
        detail=detail,
    )


def zero_locks(flags: Sequence[bool | None]) -> bool | None:
    """Whether a run set is lock-free, from its per-run lock flags.

    Args:
        flags: One entry per run: whether it locked
            (``validation.locks.RunLocks.locked``), or None when the run
            carries neither file the detector reads.

    Returns:
        False when any run locked (whatever the others record); otherwise
        None when the set is empty or any run is not recorded (not recorded
        is not "no lock"); True only when every run is recorded and none
        locked.
    """
    if any(f is True for f in flags):
        return False
    if not flags or any(f is None for f in flags):
        return None
    return True


def _lock_row(flags: Sequence[bool | None] | None) -> CriteriaResult:
    """The ``no_locks`` row (module docstring, "Model integrity: no locks").

    Args:
        flags: Per-run lock flags (None for a run not recorded), or None
            when the caller supplied none.

    Returns:
        The row: FAIL (``value`` the number of locked runs), PASS (``value``
        0) or NOT RECORDED (``value`` None).
    """
    text = (
        f"no run locked (no queue standing without discharge for "
        f"{LOCK_MIN_DURATION_S / _S_PER_MIN:g} min or more), every run recorded"
    )
    if flags is None:
        return CriteriaResult(
            name=NO_LOCKS,
            value=None,
            threshold=text,
            passed=False,
            evaluated=False,
            detail=f"{NOT_RECORDED}: no per-run lock records supplied; " + NO_LOCKS_STANDARD,
        )
    recorded = [f for f in flags if f is not None]
    n_missing = len(flags) - len(recorded)
    n_locked = sum(1 for f in recorded if f)
    flag = zero_locks(flags)
    if flag is None:
        why = (
            "no runs supplied"
            if not flags
            else f"{n_missing} of {len(flags)} run(s) carry no lock record "
            "(neither edges.parquet nor vehicles.parquet)"
        )
        return CriteriaResult(
            name=NO_LOCKS,
            value=None,
            threshold=text,
            passed=False,
            evaluated=False,
            detail=f"{NOT_RECORDED}: {why}; {NO_LOCKS_STANDARD}",
        )
    if flag:
        detail = f"no lock in {len(flags)} run(s); {NO_LOCKS_STANDARD}"
    else:
        detail = (
            f"{n_locked} of {len(recorded)} recorded run(s) locked"
            + (f"; {n_missing} run(s) not recorded" if n_missing else "")
            + f"; {NO_LOCKS_STANDARD}"
        )
    return CriteriaResult(
        name=NO_LOCKS,
        value=float(n_locked),
        threshold=text,
        passed=flag,
        evaluated=True,
        detail=detail,
    )


def _not_evaluated(
    name: str, threshold: str, *, observations_supplied: bool = False
) -> CriteriaResult:
    """An unevaluated row, saying honestly *why* it could not be evaluated.

    Args:
        name: Criterion identifier.
        threshold: Human-readable threshold description.
        observations_supplied: For the two rows scored against an
            observations artifact: the artifact was supplied but produced no
            comparable window (no station pair, no window inside the
            measurement span, no observed cell). "Input not supplied" would
            be false, and would send the reader looking for an upload that
            is already there.

    Returns:
        The row, with ``evaluated=False``.
    """
    detail = (
        "not evaluated: observations supplied, no comparable window (see the observed-data block)"
        if observations_supplied
        else "not evaluated: input not supplied"
    )
    return CriteriaResult(
        name=name,
        value=None,
        threshold=threshold,
        passed=False,
        evaluated=False,
        detail=detail,
    )


def _grid_cell_present(
    cell: tuple[float, float], grid: Sequence[tuple[float, float]], tol: float = 1e-6
) -> bool:
    return any(
        math.isclose(cell[0], g[0], abs_tol=tol) and math.isclose(cell[1], g[1], abs_tol=tol)
        for g in grid
    )


def evaluate(
    profile: CriteriaProfile | None = None,
    *,
    geh_values: Sequence[float] | None = None,
    rmspe_value: float | None = None,
    wave_speed_kmh: float | None = None,
    wave_detector: WaveDetector | None = None,
    ring_emergence: bool | None = None,
    ring_dampening: bool | None = None,
    n_seeds: int | None = None,
    sweep_grid: Sequence[tuple[float, float]] | None = None,
    observations_supplied: bool = False,
    collision_counts: Sequence[int | None] | None = None,
    lock_flags: Sequence[bool | None] | None = None,
) -> list[CriteriaResult]:
    """Evaluate acceptance criteria against measured values.

    Every check in the profile yields exactly one row. A check whose input
    is ``None`` (or NaN) is reported with ``evaluated=False`` (respectively
    a failing NaN value) rather than silently dropped — an unevaluated
    criterion is never a pass (CLAUDE.md §0.1).

    Args:
        profile: Threshold profile; ``None`` uses ``fhwa_default``
            (:class:`CriteriaProfile` defaults).
        geh_values: Per-link-hour GEH statistics (e.g.
            :func:`validation.metrics.link_hour_geh` ``.geh``).
        rmspe_value: Segment-speed RMSPE as a fraction.
        wave_speed_kmh: Emergent backward wave-front speed magnitude [km/h]
            (positive), measured with the profile's ``wave_detector`` —
            ``profile.wave_detector.measure(field).speed_kmh``.
        wave_detector: The detector that produced ``wave_speed_kmh``. When it
            is not the profile's, the row is reported as not evaluated (the
            value is kept, with both recipes named); when omitted the row
            notes that the caller did not state its detector.
        ring_emergence: Whether the Sugiyama ring emergence benchmark passed
            (``validation.ring_benchmark``).
        ring_dampening: Whether the single-AV dampening benchmark passed.
        n_seeds: Number of replicate seeds behind the reported metrics.
        sweep_grid: ``(penetration, compliance)`` cells of the published
            sensitivity sweep, as fractions. Pass only cells whose metrics
            carry replicate CIs (CLAUDE.md §7.1 "published with CIs") — the
            row checks presence of every required cell, not the CIs.
        observations_supplied: Whether an observations artifact was supplied
            for the two rows scored against one (``link_flows_geh``,
            ``speeds_rmspe``). With ``geh_values`` / ``rmspe_value`` still
            ``None`` the rows stay unevaluated, but say that the artifact
            yielded no comparable window rather than that no input was given.
        collision_counts: One entry per run of the set: its
            ``meta.json["n_collisions"]``, or None when the run does not
            record it (``validation.battery.collision_count``). Feeds the
            ``no_collisions`` row every profile carries (last): PASS only
            when every run records zero, FAIL on any collision, otherwise
            NOT RECORDED (also when ``None`` is passed: no counts supplied).
        lock_flags: One entry per run of the set: whether it locked
            (``validation.locks.RunLocks.locked``), or None when the run is
            not recorded (``validation.locks.lock_flags``). Feeds the
            ``no_locks`` row every profile carries (after ``no_collisions``,
            last): PASS only when every run is recorded and none locked,
            FAIL when any run locked, otherwise NOT RECORDED (also when
            ``None`` is passed: no records supplied).

    Returns:
        One :class:`CriteriaResult` per profile check, in table order.
    """
    p = profile if profile is not None else CriteriaProfile()
    rows: list[CriteriaResult] = []

    cmp = ">=" if p.geh_pass_inclusive else ">"
    geh_threshold_text = (
        f"GEH < {p.geh_threshold:g} for {cmp} {p.geh_pass_fraction:.0%} of link-hour comparisons"
    )
    if geh_values is None:
        rows.append(
            _not_evaluated(
                "link_flows_geh",
                geh_threshold_text,
                observations_supplied=observations_supplied,
            )
        )
    elif len(geh_values) == 0:
        rows.append(
            CriteriaResult(
                name="link_flows_geh",
                value=math.nan,
                threshold=geh_threshold_text,
                passed=False,
                evaluated=True,
                detail="no comparisons supplied",
            )
        )
    else:
        frac = sum(1 for g in geh_values if g < p.geh_threshold) / len(geh_values)
        passed = frac >= p.geh_pass_fraction if p.geh_pass_inclusive else frac > p.geh_pass_fraction
        rows.append(
            CriteriaResult(
                name="link_flows_geh",
                value=frac,
                threshold=geh_threshold_text,
                passed=passed,
                evaluated=True,
                detail=f"fraction of comparisons with GEH < {p.geh_threshold:g}",
            )
        )

    if p.rmspe_max is not None:
        rmspe_text = f"segment-speed RMSPE <= {p.rmspe_max:.0%}"
        if rmspe_value is None:
            rows.append(
                _not_evaluated(
                    "speeds_rmspe",
                    rmspe_text,
                    observations_supplied=observations_supplied,
                )
            )
        else:
            rows.append(
                CriteriaResult(
                    name="speeds_rmspe",
                    value=rmspe_value,
                    threshold=rmspe_text,
                    passed=bool(rmspe_value <= p.rmspe_max),
                    evaluated=True,
                )
            )

    lo, hi = p.wave_speed_band_kmh
    wave_text = f"backward wave speed in [{lo:g}, {hi:g}] km/h (emergent, unseeded)"
    detector_text = f"detector: {p.wave_detector.describe()}"
    if wave_speed_kmh is None:
        rows.append(_not_evaluated("wave_speed", wave_text))
    elif wave_detector is not None and wave_detector != p.wave_detector:
        rows.append(
            CriteriaResult(
                name="wave_speed",
                value=wave_speed_kmh,
                threshold=wave_text,
                passed=False,
                evaluated=False,
                detail=(
                    f"not evaluated: value measured with {wave_detector.describe()}; "
                    f"profile requires {p.wave_detector.describe()}"
                ),
            )
        )
    else:
        in_band = bool(lo <= wave_speed_kmh <= hi)  # NaN compares False
        notes = [detector_text]
        if wave_detector is None:
            notes.append("caller did not state which detector produced the value")
        if not math.isfinite(wave_speed_kmh):
            notes.append("no backward wave detected")
        rows.append(
            CriteriaResult(
                name="wave_speed",
                value=wave_speed_kmh,
                threshold=wave_text,
                passed=in_band,
                evaluated=True,
                detail="; ".join(notes),
            )
        )

    if p.require_ring_emergence:
        text = "Sugiyama ring emergence benchmark reproduced"
        if ring_emergence is None:
            rows.append(_not_evaluated("ring_emergence", text))
        else:
            rows.append(
                CriteriaResult(
                    name="ring_emergence",
                    value=float(ring_emergence),
                    threshold=text,
                    passed=bool(ring_emergence),
                    evaluated=True,
                )
            )

    if p.require_ring_dampening:
        text = "Stern single-AV dampening benchmark reproduced"
        if ring_dampening is None:
            rows.append(_not_evaluated("ring_dampening", text))
        else:
            rows.append(
                CriteriaResult(
                    name="ring_dampening",
                    value=float(ring_dampening),
                    threshold=text,
                    passed=bool(ring_dampening),
                    evaluated=True,
                )
            )

    seeds_text = f"n_seeds >= {p.min_seeds}"
    if n_seeds is None:
        rows.append(_not_evaluated("n_seeds", seeds_text))
    else:
        rows.append(
            CriteriaResult(
                name="n_seeds",
                value=float(n_seeds),
                threshold=seeds_text,
                passed=n_seeds >= p.min_seeds,
                evaluated=True,
            )
        )

    if p.require_sensitivity_grid:
        pens = "{" + ", ".join(f"{v:.0%}" for v in p.required_penetrations) + "}"
        comps = "{" + ", ".join(f"{v:.0%}" for v in p.required_compliances) + "}"
        grid_text = f"penetration {pens} x compliance {comps} grid published with CIs"
        if sweep_grid is None:
            rows.append(_not_evaluated("sensitivity_grid", grid_text))
        else:
            required = [
                (pen, comp) for pen in p.required_penetrations for comp in p.required_compliances
            ]
            missing = [c for c in required if not _grid_cell_present(c, sweep_grid)]
            n_present = len(required) - len(missing)
            detail = f"{n_present}/{len(required)} required cells present"
            if missing:
                detail += "; missing: " + ", ".join(
                    f"({pen:.0%}, {comp:.0%})" for pen, comp in missing
                )
            rows.append(
                CriteriaResult(
                    name="sensitivity_grid",
                    value=n_present / len(required),
                    threshold=grid_text,
                    passed=not missing,
                    evaluated=True,
                    detail=detail,
                )
            )

    # Model integrity, in every profile (2026-10-04, WP-98; locks 2026-10-07).
    rows.append(_collision_row(collision_counts))
    rows.append(_lock_row(lock_flags))
    return rows
