"""Acceptance criteria (CLAUDE.md §7.1) as data, not prose.

Encodes acceptance tables as :class:`CriteriaProfile` records held in the
:data:`CRITERIA_PROFILES` registry (``get_profile(name)``) and evaluates
supplied measurements into honest pass/fail rows — no rounding games; a
missing input is reported as *not evaluated and failing* (CLAUDE.md §0.1).

Every profile carries a ``source`` string stating exactly which document,
section and table its numbers were transcribed from, what was verified in
this repository's session and how, and which fields are FlowState's own
conventions rather than the document's. Read those strings before quoting a
profile in a report. Summary of the verification (2026-09-03):

* **FHWA Traffic Analysis Toolbox Vol. III, 2004** (FHWA-HRT-04-040), §5.6
  "Calibration Targets", verified on the HTML edition at
  https://ops.fhwa.dot.gov/trafficanalysistools/tat_vol3/sect5.htm, where the
  Wisconsin DOT freeway calibration table is captioned "Table 4" (attributed
  to WisDOT District 2, Paramics Calibration and Validation Guidelines,
  Technical Report I-33, June 2002). Rows: individual link flows within 15%
  (700–2,700 veh/h), within 100 veh/h (< 700), within 400 veh/h (> 2,700),
  each for > 85% of cases; sum of all link flows within 5%; **GEH < 5 for
  individual link flows in > 85% of cases**; GEH < 4 for the sum; journey
  times within 15% (or 1 min if higher) for > 85% of cases; visual audits to
  the analyst's satisfaction. CLAUDE.md §7.1 refers to this as "Table 5";
  the HTML edition numbers it Table 4 — the PDF numbering was not checked.
* **FHWA Traffic Analysis Toolbox Vol. III, 2019 update** (FHWA-HOP-18-036),
  Chapter 5 "Model Calibration", verified at
  https://ops.fhwa.dot.gov/publications/fhwahop18036/chapter5.htm: it
  contains **no GEH or 85% target**. It derives project-specific acceptance
  envelopes from observed-data variability (Criteria I–IV: 95% of simulated
  outputs inside the time-variant envelope; two-thirds inside the
  representative-day band; bounded dynamic absolute and systematic error)
  and states "The analyst does not need to calibrate multiple model runs
  generated by varying the random number seeds." The fixed GEH/85% wording
  that CLAUDE.md attributes to "FHWA-HOP-18-036 usage" is therefore the
  2004 edition's (and its DOT descendants'), not the 2019 text.
* **Oregon DOT, Protocol for VISSIM Simulation (June 2011)**, read from the
  PDF at https://www.oregon.gov/odot/Planning/Documents/APMv2_Add15A.pdf,
  §6.1 Tables 6-1/6-2, §6.2, §6.3 Table 6-3, §6.9.
* **TxDOT Traffic and Safety Analysis Procedures Manual, Chapter 13
  "Microsimulation Analysis"**, §13.5.2 "Acceptability Criteria" and
  §13.5.2.3 "Throughput", read at
  https://www.txdot.gov/manuals/des/tsp/chapter-13-microsimulation-analysis/13-5-calibration/13-5-2-acceptability-criteria.html
  (Tables 13-4 and 13-5). The travel-time criteria of §13.5.2.2 (Table
  13-3) are equations published as images and could not be read.

The segment-speed RMSPE bound, the emergent backward wave-speed band, the
ring benchmarks, the ≥ 20-seed rule and the penetration × compliance grid are
FlowState requirements from CLAUDE.md §7.1/§0.6, present in every profile and
labeled as such in ``source``; no DOT document above prescribes them.
"""

from __future__ import annotations

import math
from collections.abc import Sequence
from dataclasses import dataclass, field

from flowstate_core.constants import WAVE_SPEED_BAND_KMH

#: Penetrations of the CLAUDE.md §7.1 sensitivity grid (fractions).
REQUIRED_PENETRATIONS: tuple[float, ...] = (0.01, 0.02, 0.05, 0.10, 0.15, 0.20)
#: Compliances of the CLAUDE.md §7.1 sensitivity grid (fractions).
REQUIRED_COMPLIANCES: tuple[float, ...] = (0.25, 0.5, 0.8, 1.0)

_FLOWSTATE_ROWS = (
    "The segment-speed RMSPE <= 15% bound is FlowState's own convention "
    "(CLAUDE.md §7.1, 'common microsim practice'); the 14-22 km/h emergent "
    "backward wave-speed band is the empirical stop-and-go literature value "
    "(flowstate_core.constants.WAVE_SPEED_BAND_KMH); the ring emergence/dampening "
    "rows reproduce Sugiyama et al. (2008) and Stern et al. (2018) per CLAUDE.md "
    "§3.2.1; min_seeds = 20 and the penetration {1,2,5,10,15,20}% x compliance "
    "{25,50,80,100}% grid are CLAUDE.md §0.6/§7.1 internal standards. None of "
    "these is prescribed by the cited DOT/FHWA documents."
)

FHWA_DEFAULT_SOURCE = (
    "FlowState default profile (CLAUDE.md §7.1). GEH < 5 for >= 85% of link-hour "
    "comparisons transcribes the 'GEH Statistic < 5 for Individual Link Flows: "
    "> 85% of cases' row of the Wisconsin DOT freeway model calibration criteria "
    "table (captioned 'Table 4' on the HTML edition) in §5.6 'Calibration Targets' "
    "of the FHWA Traffic Analysis Toolbox Vol. III, 2004 (FHWA-HRT-04-040), verified "
    "2026-09-03 at https://ops.fhwa.dot.gov/trafficanalysistools/tat_vol3/sect5.htm; "
    "the source says '> 85%' where this profile, like CLAUDE.md, uses '>= 85%' "
    "(geh_pass_inclusive=True). The 2019 update (FHWA-HOP-18-036) Chapter 5, "
    "verified the same day at https://ops.fhwa.dot.gov/publications/fhwahop18036/chapter5.htm, "
    "prescribes no GEH or 85% target (it builds data-driven variation envelopes, "
    "Criteria I-IV) and says the analyst need not calibrate multiple random-seed "
    "runs; the citation of FHWA-HOP-18-036 for the GEH wording elsewhere in this "
    "repository is therefore a citation of the toolbox lineage, not of the 2019 "
    "text. " + _FLOWSTATE_ROWS
)

FHWA_TAT3_2004_SOURCE = (
    "FHWA Traffic Analysis Toolbox Vol. III (2004, FHWA-HRT-04-040), §5.6 "
    "'Calibration Targets', Wisconsin DOT freeway model calibration criteria "
    "(captioned 'Table 4' on the HTML edition at "
    "https://ops.fhwa.dot.gov/trafficanalysistools/tat_vol3/sect5.htm, verified "
    "2026-09-03; attributed there to WisDOT District 2, Paramics Calibration and "
    "Validation Guidelines, Technical Report I-33, June 2002). Transcribed row: "
    "'GEH Statistic < 5 for Individual Link Flows: > 85% of cases' — strict "
    "'> 85%' (geh_pass_inclusive=False). Rows of that table NOT evaluated by "
    "FlowState: individual link flows within 15% / 100 veh/h / 400 veh/h by flow "
    "band for > 85% of cases; sum of all link flows within 5%; GEH < 4 for the sum "
    "of all link flows; journey times within 15% (or 1 min, if higher) for > 85% "
    "of cases; visual audits of speed-flow relationships and bottleneck queuing "
    "'to analyst's satisfaction'. The table defines no RMSPE speed bound, so this "
    "profile produces no speeds_rmspe row (rmspe_max=None). The 2004 volume gives "
    "no fixed minimum run count (its §5 example uses ten replications to estimate "
    "a parameter within 5%), so min_seeds keeps FlowState's 20 (CLAUDE.md §0.6). " + _FLOWSTATE_ROWS
)

ODOT_VISSIM_2011_SOURCE = (
    "Oregon DOT, 'Protocol for VISSIM Simulation' (June 2011), read 2026-09-03 "
    "from the PDF at https://www.oregon.gov/odot/Planning/Documents/APMv2_Add15A.pdf. "
    "§6.1 'Volume/Density', Table 6-2 'Traffic Volume Calibration Criteria': "
    "'GEH < 5.0 — At least 85% of freeway links within the calibration area' "
    "(transcribed: geh_threshold=5.0, geh_pass_fraction=0.85, inclusive). Rows of "
    "Table 6-2 NOT evaluated by FlowState: GEH < 5.0 for all entry and exit "
    "locations, all entrance and exit ramps, and all intersection turn movements "
    "> 100 veh/h; individual flows within +/-400 veh/h for flows exceeding 2,700 "
    "veh/h on at least 85% of applicable mainline links; sum of all link flows "
    "within 5%. Table 6-1 'GEH Statistic Guidelines': GEH < 5.0 acceptable fit; "
    "5.0 <= GEH <= 10.0 caution (possible model error or bad data); GEH > 10.0 "
    "unacceptable. §6.9 'Minimum Number of Simulation Runs': 'All model results "
    "reported shall be an average of a minimum of 10 simulation runs with "
    "different random number seeds' (transcribed: min_seeds=10; FlowState's own "
    "20-seed headline rule, CLAUDE.md §0.6, still drives the underpowered flag of "
    "validation.metrics.aggregate). §6.2 'Speed': spot speeds within 10 percent "
    "of observed at key calibration locations and, where network-wide data exist, "
    "within 10 mph on at least 85 percent of freeway links — a per-location "
    "tolerance, not an RMSPE, so this profile defines no RMSPE bound and produces "
    "no speeds_rmspe row (rmspe_max=None). §6.3 Table 6-3 'Travel Time Calibration "
    "Criteria' (+/-1 min for routes under 7 min, +/-15% over 7 min; attributed to "
    "FHWA TAT Vol. III / Wisconsin DOT) is not evaluated by FlowState. " + _FLOWSTATE_ROWS
)

TXDOT_TSAP_CH13_SOURCE = (
    "TxDOT Traffic and Safety Analysis Procedures Manual, Chapter 13 "
    "'Microsimulation Analysis', §13.5.2 'Acceptability Criteria' and §13.5.2.3 "
    "'Throughput', read 2026-09-03 at https://www.txdot.gov/manuals/des/tsp/"
    "chapter-13-microsimulation-analysis/13-5-calibration/13-5-2-acceptability-criteria.html "
    "(no revision date shown). Table 13-4 'GEH Statistic Guidelines': < 3.0 "
    "acceptable fit; 3.0 to 5.0 acceptable for local roadway facilities; > 5.0 "
    "unacceptable. Table 13-5 'Throughput Calibration Targets': GEH < 3.0 for all "
    "state facility segments, all entry/exit points and all ramps; GEH < 5.0 for "
    "at least 85% of local roadway segments; sum of all segment flows within 5%. "
    "This profile transcribes the state-facility row, the applicable one for a "
    "freeway corridor: geh_threshold=3.0 on every comparison "
    "(geh_pass_fraction=1.0); the local-roadway row would be 5.0 for >= 85%. The "
    "manual states 'For all FHWA related projects, it is necessary to use the "
    "FHWA 2019 Guidelines. For non-FHWA projects, calibration criteria is "
    "typically determined during project scoping and based on discussions with "
    "the TxDOT project manager.' NOT transcribed: the travel-time criteria of "
    "§13.5.2.2 Table 13-3 (free-flowing and interrupted-flow tolerance equations "
    "published as images, unreadable in the session); the sum-of-flows row; any "
    "minimum run count (not located on the pages consulted, so min_seeds keeps "
    "FlowState's 20, CLAUDE.md §0.6). The manual defines no RMSPE speed bound, so "
    "no speeds_rmspe row is produced (rmspe_max=None). " + _FLOWSTATE_ROWS
)


@dataclass(frozen=True)
class CriteriaProfile:
    """One named set of acceptance thresholds (CLAUDE.md §7.1 table).

    The defaults reproduce the ``fhwa_default`` profile, so
    ``CriteriaProfile()`` is that profile.

    Attributes:
        name: Profile identifier (recorded in reports).
        source: Provenance: document, section, table, what was verified and
            how, and which fields are FlowState conventions. Never empty.
        geh_threshold: Per-comparison GEH acceptance bound (strict ``<``).
        geh_pass_fraction: Minimum fraction of link-hour comparisons that
            must satisfy the GEH bound.
        geh_pass_inclusive: Whether the fraction test is ``>=`` (True) or
            strict ``>`` (False, the 2004 FHWA table's "> 85% of cases").
        rmspe_max: Maximum segment-speed RMSPE as a fraction (inclusive), or
            ``None`` when the profile's source defines no RMSPE bound — the
            ``speeds_rmspe`` row is then not produced.
        wave_speed_band_kmh: Acceptance band for the emergent backward
            wave-front speed magnitude [km/h], inclusive on both ends.
        min_seeds: Minimum replicate count for headline reporting.
        require_ring_emergence: Include the Sugiyama ring emergence check.
        require_ring_dampening: Include the Stern single-AV dampening check.
        require_sensitivity_grid: Include the penetration × compliance grid
            check (CLAUDE.md §7.1 "Sensitivity" row).
        required_penetrations: Penetration levels the grid must contain.
        required_compliances: Compliance levels the grid must contain.
    """

    name: str = "fhwa_default"
    source: str = FHWA_DEFAULT_SOURCE
    geh_threshold: float = 5.0
    geh_pass_fraction: float = 0.85
    geh_pass_inclusive: bool = True
    rmspe_max: float | None = 0.15
    wave_speed_band_kmh: tuple[float, float] = field(default=WAVE_SPEED_BAND_KMH)
    min_seeds: int = 20
    require_ring_emergence: bool = True
    require_ring_dampening: bool = True
    require_sensitivity_grid: bool = True
    required_penetrations: tuple[float, ...] = REQUIRED_PENETRATIONS
    required_compliances: tuple[float, ...] = REQUIRED_COMPLIANCES

    def __post_init__(self) -> None:
        if not self.source.strip():
            raise ValueError(f"profile {self.name!r} needs a non-empty source")
        if not 0.0 < self.geh_pass_fraction <= 1.0:
            raise ValueError(f"geh_pass_fraction must be in (0, 1], got {self.geh_pass_fraction}")


FHWA_DEFAULT = CriteriaProfile()

FHWA_TAT3_2004 = CriteriaProfile(
    name="fhwa_tat3_2004",
    source=FHWA_TAT3_2004_SOURCE,
    geh_threshold=5.0,
    geh_pass_fraction=0.85,
    geh_pass_inclusive=False,
    rmspe_max=None,
)

ODOT_VISSIM_2011 = CriteriaProfile(
    name="odot_vissim_2011",
    source=ODOT_VISSIM_2011_SOURCE,
    geh_threshold=5.0,
    geh_pass_fraction=0.85,
    geh_pass_inclusive=True,
    rmspe_max=None,
    min_seeds=10,
)

TXDOT_TSAP_CH13 = CriteriaProfile(
    name="txdot_tsap_ch13",
    source=TXDOT_TSAP_CH13_SOURCE,
    geh_threshold=3.0,
    geh_pass_fraction=1.0,
    geh_pass_inclusive=True,
    rmspe_max=None,
)

CRITERIA_PROFILES: dict[str, CriteriaProfile] = {
    p.name: p for p in (FHWA_DEFAULT, FHWA_TAT3_2004, ODOT_VISSIM_2011, TXDOT_TSAP_CH13)
}
"""Selectable profiles by name (CLAUDE.md §7.1: state-DOT variants)."""


def get_profile(name: str) -> CriteriaProfile:
    """Look up a registered :class:`CriteriaProfile` by name.

    Args:
        name: Key of :data:`CRITERIA_PROFILES`.

    Returns:
        The profile.

    Raises:
        KeyError: Unknown name; the message lists the available profiles.
    """
    try:
        return CRITERIA_PROFILES[name]
    except KeyError as exc:
        raise KeyError(
            f"unknown criteria profile {name!r}; available: {sorted(CRITERIA_PROFILES)}"
        ) from exc


@dataclass(frozen=True)
class CriteriaResult:
    """One evaluated acceptance-criterion row.

    Attributes:
        name: Criterion identifier.
        value: Measured value, or ``None`` when the input was not supplied.
        threshold: Human-readable threshold description.
        passed: Honest pass/fail; always ``False`` when not evaluated.
        evaluated: Whether an input was available to evaluate.
        detail: Optional explanatory note.
    """

    name: str
    value: float | None
    threshold: str
    passed: bool
    evaluated: bool
    detail: str = ""


def _not_evaluated(name: str, threshold: str) -> CriteriaResult:
    return CriteriaResult(
        name=name,
        value=None,
        threshold=threshold,
        passed=False,
        evaluated=False,
        detail="not evaluated: input not supplied",
    )


def _grid_cell_present(
    cell: tuple[float, float], grid: Sequence[tuple[float, float]], tol: float = 1e-6
) -> bool:
    return any(
        math.isclose(cell[0], g[0], abs_tol=tol) and math.isclose(cell[1], g[1], abs_tol=tol)
        for g in grid
    )


def evaluate(
    profile: CriteriaProfile | None = None,
    *,
    geh_values: Sequence[float] | None = None,
    rmspe_value: float | None = None,
    wave_speed_kmh: float | None = None,
    ring_emergence: bool | None = None,
    ring_dampening: bool | None = None,
    n_seeds: int | None = None,
    sweep_grid: Sequence[tuple[float, float]] | None = None,
) -> list[CriteriaResult]:
    """Evaluate acceptance criteria against measured values.

    Every check in the profile yields exactly one row. A check whose input
    is ``None`` (or NaN) is reported with ``evaluated=False`` (respectively
    a failing NaN value) rather than silently dropped — an unevaluated
    criterion is never a pass (CLAUDE.md §0.1).

    Args:
        profile: Threshold profile; ``None`` uses ``fhwa_default``
            (:class:`CriteriaProfile` defaults).
        geh_values: Per-link-hour GEH statistics (e.g.
            :func:`validation.metrics.link_hour_geh` ``.geh``).
        rmspe_value: Segment-speed RMSPE as a fraction.
        wave_speed_kmh: Emergent backward wave-front speed magnitude [km/h]
            (positive; e.g. ``Metrics.wave_speed_kmh``).
        ring_emergence: Whether the Sugiyama ring emergence benchmark passed
            (``validation.ring_benchmark``).
        ring_dampening: Whether the single-AV dampening benchmark passed.
        n_seeds: Number of replicate seeds behind the reported metrics.
        sweep_grid: ``(penetration, compliance)`` cells of the published
            sensitivity sweep, as fractions. Pass only cells whose metrics
            carry replicate CIs (CLAUDE.md §7.1 "published with CIs") — the
            row checks presence of every required cell, not the CIs.

    Returns:
        One :class:`CriteriaResult` per profile check, in table order.
    """
    p = profile if profile is not None else CriteriaProfile()
    rows: list[CriteriaResult] = []

    cmp = ">=" if p.geh_pass_inclusive else ">"
    geh_threshold_text = (
        f"GEH < {p.geh_threshold:g} for {cmp} {p.geh_pass_fraction:.0%} of link-hour comparisons"
    )
    if geh_values is None:
        rows.append(_not_evaluated("link_flows_geh", geh_threshold_text))
    elif len(geh_values) == 0:
        rows.append(
            CriteriaResult(
                name="link_flows_geh",
                value=math.nan,
                threshold=geh_threshold_text,
                passed=False,
                evaluated=True,
                detail="no comparisons supplied",
            )
        )
    else:
        frac = sum(1 for g in geh_values if g < p.geh_threshold) / len(geh_values)
        passed = frac >= p.geh_pass_fraction if p.geh_pass_inclusive else frac > p.geh_pass_fraction
        rows.append(
            CriteriaResult(
                name="link_flows_geh",
                value=frac,
                threshold=geh_threshold_text,
                passed=passed,
                evaluated=True,
                detail=f"fraction of comparisons with GEH < {p.geh_threshold:g}",
            )
        )

    if p.rmspe_max is not None:
        rmspe_text = f"segment-speed RMSPE <= {p.rmspe_max:.0%}"
        if rmspe_value is None:
            rows.append(_not_evaluated("speeds_rmspe", rmspe_text))
        else:
            rows.append(
                CriteriaResult(
                    name="speeds_rmspe",
                    value=rmspe_value,
                    threshold=rmspe_text,
                    passed=bool(rmspe_value <= p.rmspe_max),
                    evaluated=True,
                )
            )

    lo, hi = p.wave_speed_band_kmh
    wave_text = f"backward wave speed in [{lo:g}, {hi:g}] km/h (emergent, unseeded)"
    if wave_speed_kmh is None:
        rows.append(_not_evaluated("wave_speed", wave_text))
    else:
        in_band = bool(lo <= wave_speed_kmh <= hi)  # NaN compares False
        detail = "" if math.isfinite(wave_speed_kmh) else "no backward wave detected"
        rows.append(
            CriteriaResult(
                name="wave_speed",
                value=wave_speed_kmh,
                threshold=wave_text,
                passed=in_band,
                evaluated=True,
                detail=detail,
            )
        )

    if p.require_ring_emergence:
        text = "Sugiyama ring emergence benchmark reproduced"
        if ring_emergence is None:
            rows.append(_not_evaluated("ring_emergence", text))
        else:
            rows.append(
                CriteriaResult(
                    name="ring_emergence",
                    value=float(ring_emergence),
                    threshold=text,
                    passed=bool(ring_emergence),
                    evaluated=True,
                )
            )

    if p.require_ring_dampening:
        text = "Stern single-AV dampening benchmark reproduced"
        if ring_dampening is None:
            rows.append(_not_evaluated("ring_dampening", text))
        else:
            rows.append(
                CriteriaResult(
                    name="ring_dampening",
                    value=float(ring_dampening),
                    threshold=text,
                    passed=bool(ring_dampening),
                    evaluated=True,
                )
            )

    seeds_text = f"n_seeds >= {p.min_seeds}"
    if n_seeds is None:
        rows.append(_not_evaluated("n_seeds", seeds_text))
    else:
        rows.append(
            CriteriaResult(
                name="n_seeds",
                value=float(n_seeds),
                threshold=seeds_text,
                passed=n_seeds >= p.min_seeds,
                evaluated=True,
            )
        )

    if p.require_sensitivity_grid:
        pens = "{" + ", ".join(f"{v:.0%}" for v in p.required_penetrations) + "}"
        comps = "{" + ", ".join(f"{v:.0%}" for v in p.required_compliances) + "}"
        grid_text = f"penetration {pens} x compliance {comps} grid published with CIs"
        if sweep_grid is None:
            rows.append(_not_evaluated("sensitivity_grid", grid_text))
        else:
            required = [
                (pen, comp) for pen in p.required_penetrations for comp in p.required_compliances
            ]
            missing = [c for c in required if not _grid_cell_present(c, sweep_grid)]
            n_present = len(required) - len(missing)
            detail = f"{n_present}/{len(required)} required cells present"
            if missing:
                detail += "; missing: " + ", ".join(
                    f"({pen:.0%}, {comp:.0%})" for pen, comp in missing
                )
            rows.append(
                CriteriaResult(
                    name="sensitivity_grid",
                    value=n_present / len(required),
                    threshold=grid_text,
                    passed=not missing,
                    evaluated=True,
                    detail=detail,
                )
            )
    return rows
