"""Outreach target list for FlowState: organisations and the roles to reach, as a spreadsheet.

Writes ``docs/business/outreach_targets.xlsx`` (sheets: Targets, How to use) and
``docs/business/outreach_targets.csv``. Organisations only, with the role to reach and
the public channel; no personal e-mail addresses are invented. Named people appear only
where they are public authors or programme leads. Run from the repo root::

    uv run --no-sync --with openpyxl python scripts/business_outreach_list.py
"""

from __future__ import annotations

import csv
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

REPO = Path(__file__).resolve().parents[1]
OUT_DIR = REPO / "docs" / "business"

# (organisation, type, region, priority 1-3, why, role to reach, named public contact, website, channel)
STATE_DOTS = [
    (
        "Tennessee DOT (TDOT)",
        "TN",
        1,
        "Owns the I-24 corridor and the SMART Corridor gantries; the flagship results are the introduction; holds the radar counts",
        "Director of Traffic Operations (TSMO); Long Range Planning modeling lead; Research Office",
        "tn.gov/tdot",
    ),
    (
        "Texas DOT (TxDOT)",
        "TX",
        1,
        "Named second target; TxDOT analysis procedures are a selectable criteria profile; Dallas demo corridor in the gallery",
        "Traffic Safety / Traffic Operations Division; TPP modeling section; Research and Technology Implementation",
        "txdot.gov",
    ),
    (
        "Caltrans",
        "CA",
        1,
        "PeMS detector data is public and the loader exists; DOT-style validation case with measured counts",
        "Division of Traffic Operations; Office of Traffic Management (Mobility); District 4/7 operations",
        "dot.ca.gov",
    ),
    (
        "Florida DOT (FDOT)",
        "FL",
        1,
        "Large ITS programme (I-4 VSL history), unit-cost tables published, active microsimulation guidance",
        "State Traffic Engineering and Operations Office; TSM&O programme; Systems Implementation Office",
        "fdot.gov",
    ),
    (
        "Georgia DOT",
        "GA",
        1,
        "Metro Atlanta congestion; managed lanes; active TSMO office",
        "Office of Traffic Operations; Office of Planning modeling",
        "dot.ga.gov",
    ),
    (
        "Virginia DOT (VDOT)",
        "VA",
        1,
        "Publishes calibration research (VTRC); I-66/I-95 managed and VSL corridors",
        "Operations Division; Transportation and Mobility Planning; VTRC",
        "virginiadot.org",
    ),
    (
        "Washington State DOT (WSDOT)",
        "WA",
        1,
        "Long-running VSL / active traffic management on I-5 and SR 520; strong TSMO culture",
        "Traffic Operations; TSMO programme; Multimodal Planning",
        "wsdot.wa.gov",
    ),
    (
        "Minnesota DOT (MnDOT)",
        "MN",
        1,
        "Twin Cities smart-lane VSL history; University of Minnesota (Stern) nearby",
        "Regional Transportation Management Center; Office of Traffic Engineering",
        "dot.state.mn.us",
    ),
    (
        "Michigan DOT (MDOT)",
        "MI",
        1,
        "Statewide probe data buyer; work-zone VSL trials",
        "Bureau of Field Services, ITS programme; Statewide Planning",
        "michigan.gov/mdot",
    ),
    (
        "Colorado DOT (CDOT)",
        "CO",
        1,
        "I-70 mountain corridor VSL; RoadX innovation programme",
        "Traffic Safety and Engineering; ITS branch",
        "codot.gov",
    ),
    (
        "Arizona DOT (ADOT)",
        "AZ",
        1,
        "Phoenix freeway management system; MAG modeling nearby",
        "Traffic Operations Center; Transportation Systems Management and Operations",
        "azdot.gov",
    ),
    (
        "North Carolina DOT (NCDOT)",
        "NC",
        1,
        "Probe-data cost comparisons published; growing TSMO",
        "Transportation Mobility and Safety Division; Transportation Planning modeling",
        "ncdot.gov",
    ),
    (
        "Ohio DOT (ODOT)",
        "OH",
        1,
        "ODOT VISSIM protocol is a selectable criteria profile",
        "Office of Traffic Operations; Modeling and Forecasting",
        "transportation.ohio.gov",
    ),
    (
        "Pennsylvania DOT (PennDOT)",
        "PA",
        2,
        "Large ITS programme; regional TMCs",
        "Bureau of Maintenance and Operations, TSMO",
        "penndot.pa.gov",
    ),
    (
        "New York State DOT (NYSDOT)",
        "NY",
        2,
        "Publishes consultant rate ceilings; large modeling practice",
        "Office of Traffic Safety and Mobility; Statewide Planning",
        "dot.ny.gov",
    ),
    (
        "Illinois DOT (IDOT)",
        "IL",
        2,
        "Chicago expressway management; CMAP modeling nearby",
        "Bureau of Operations; ITS programme",
        "idot.illinois.gov",
    ),
    (
        "Maryland DOT SHA",
        "MD",
        2,
        "CHART operations programme; University of Maryland CATT Lab",
        "Office of Transportation Mobility and Operations",
        "roads.maryland.gov",
    ),
    (
        "Utah DOT (UDOT)",
        "UT",
        2,
        "Nationally known TSMO and performance measures culture",
        "Traffic Management Division; TSMO",
        "udot.utah.gov",
    ),
    (
        "Oregon DOT (ODOT)",
        "OR",
        2,
        "Portland ATM / VSL on OR 217 and I-5; Metro modeling nearby",
        "Traffic-Roadway Section; ITS unit",
        "oregon.gov/odot",
    ),
    (
        "New Jersey DOT",
        "NJ",
        2,
        "Dense corridors; NJ traffic operations centers",
        "Bureau of Transportation Systems Management",
        "nj.gov/transportation",
    ),
    (
        "Massachusetts DOT",
        "MA",
        2,
        "Boston corridors; Boston MPO modeling",
        "Highway Division, Traffic and Safety Engineering",
        "mass.gov/orgs/massachusetts-department-of-transportation",
    ),
    (
        "Nevada DOT",
        "NV",
        2,
        "Las Vegas FAST regional traffic management",
        "Traffic Operations; FAST (with RTC of Southern Nevada)",
        "dot.nv.gov",
    ),
    (
        "Wisconsin DOT",
        "WI",
        2,
        "Milwaukee freeway management; UW TOPS Lab nearby",
        "Bureau of Traffic Operations",
        "wisconsindot.gov",
    ),
    (
        "Missouri DOT (MoDOT)",
        "MO",
        2,
        "St. Louis and Kansas City TMCs",
        "Traffic Management and Operations",
        "modot.org",
    ),
    (
        "Indiana DOT (INDOT)",
        "IN",
        2,
        "Purdue JTRP research partnership; probe-data leader",
        "Traffic Management; Research and Development",
        "in.gov/indot",
    ),
    (
        "Kentucky Transportation Cabinet",
        "KY",
        2,
        "Publishes VISSIM calibration reports for corridor studies",
        "Division of Planning; Traffic Operations",
        "transportation.ky.gov",
    ),
    (
        "South Carolina DOT",
        "SC",
        3,
        "Growing interstate congestion; ITS expansion",
        "Traffic Engineering; ITS",
        "scdot.org",
    ),
    (
        "Alabama DOT (ALDOT)",
        "AL",
        3,
        "Birmingham corridors",
        "Traffic Operations",
        "dot.state.al.us",
    ),
    (
        "Louisiana DOTD",
        "LA",
        3,
        "Baton Rouge / New Orleans corridors",
        "ITS section; Traffic Engineering",
        "dotd.la.gov",
    ),
    ("Mississippi DOT", "MS", 3, "", "Traffic Engineering", "mdot.ms.gov"),
    ("Arkansas DOT", "AR", 3, "", "Transportation Planning and Policy; Traffic", "ardot.gov"),
    ("Oklahoma DOT", "OK", 3, "", "Traffic Engineering", "oklahoma.gov/odot"),
    (
        "Kansas DOT",
        "KS",
        3,
        "Kansas City metro with MoDOT and MARC",
        "Bureau of Transportation Safety; Traffic",
        "ksdot.gov",
    ),
    ("Nebraska DOT", "NE", 3, "", "Traffic Engineering", "dot.nebraska.gov"),
    (
        "Iowa DOT",
        "IA",
        3,
        "INRIX statewide case study; Iowa State InTrans nearby",
        "Traffic Operations; Systems Planning",
        "iowadot.gov",
    ),
    (
        "Connecticut DOT",
        "CT",
        3,
        "I-95 corridor; CRCOG modeling",
        "Bureau of Engineering and Construction, Traffic",
        "portal.ct.gov/dot",
    ),
    (
        "Delaware DOT (DelDOT)",
        "DE",
        3,
        "Integrated TMC; small agile agency",
        "Transportation Management Center",
        "deldot.gov",
    ),
    ("District DOT (DDOT)", "DC", 3, "", "Traffic Operations and Safety", "ddot.dc.gov"),
    ("Rhode Island DOT", "RI", 3, "", "Traffic Management", "dot.ri.gov"),
    ("New Hampshire DOT", "NH", 3, "", "Bureau of Traffic", "nh.gov/dot"),
    (
        "Vermont Agency of Transportation",
        "VT",
        3,
        "",
        "Operations and Safety",
        "vtrans.vermont.gov",
    ),
    ("Maine DOT", "ME", 3, "", "Traffic Engineering", "maine.gov/mdot"),
    ("West Virginia DOT", "WV", 3, "", "Traffic Engineering", "transportation.wv.gov"),
    ("New Mexico DOT", "NM", 3, "", "Traffic Technical Support", "dot.nm.gov"),
    ("Idaho Transportation Department", "ID", 3, "", "Traffic Services", "itd.idaho.gov"),
    ("Montana DOT", "MT", 3, "", "Traffic and Safety", "mdt.mt.gov"),
    (
        "Wyoming DOT",
        "WY",
        3,
        "I-80 VSL corridor, one of the oldest rural VSL systems",
        "Traffic Program; ITS",
        "dot.state.wy.us",
    ),
    ("North Dakota DOT", "ND", 3, "", "Traffic Operations", "dot.nd.gov"),
    ("South Dakota DOT", "SD", 3, "", "Operations", "dot.sd.gov"),
    ("Alaska DOT&PF", "AK", 3, "", "Traffic and Safety", "dot.alaska.gov"),
    (
        "Hawaii DOT",
        "HI",
        3,
        "H-1 congestion in Honolulu",
        "Highways Division, Traffic Branch",
        "hidot.hawaii.gov",
    ),
    ("Puerto Rico DTOP", "PR", 3, "", "Highways and Transportation Authority", "dtop.pr.gov"),
]

MPOS = [
    (
        "Greater Nashville Regional Council (GNRC)",
        "TN",
        1,
        "Nashville area MPO; the flagship corridor is in its region",
        "Transportation Director; travel demand modeling lead",
        "gnrc.org",
    ),
    (
        "North Central Texas Council of Governments (NCTCOG)",
        "TX",
        1,
        "Named second target; large in-house modeling group; Dallas demo corridor",
        "Transportation Department, Model Development; Congestion Management",
        "nctcog.org",
    ),
    (
        "Houston-Galveston Area Council (H-GAC)",
        "TX",
        1,
        "Large freeway network; active modeling group",
        "Transportation Planning, Travel Modeling",
        "h-gac.com",
    ),
    (
        "Capital Area MPO (CAMPO, Austin)",
        "TX",
        2,
        "",
        "Modeling and Data; Regional Planning",
        "campotexas.org",
    ),
    (
        "Alamo Area MPO (San Antonio)",
        "TX",
        2,
        "",
        "Transportation Planning, Modeling",
        "alamoareampo.org",
    ),
    (
        "Southern California Association of Governments (SCAG)",
        "CA",
        1,
        "Largest MPO; PeMS data region",
        "Modeling and Forecasting Department",
        "scag.ca.gov",
    ),
    (
        "Metropolitan Transportation Commission (MTC, Bay Area)",
        "CA",
        1,
        "Bay Area; PeMS; Berkeley labs nearby",
        "Data and Modeling; Operations (Bay Area Forward)",
        "mtc.ca.gov",
    ),
    (
        "San Diego Association of Governments (SANDAG)",
        "CA",
        2,
        "Strong modeling shop (ABM)",
        "Data Science and Modeling",
        "sandag.org",
    ),
    (
        "Sacramento Area Council of Governments (SACOG)",
        "CA",
        2,
        "",
        "Modeling and Analytics",
        "sacog.org",
    ),
    (
        "Atlanta Regional Commission (ARC)",
        "GA",
        1,
        "Atlanta freeways; strong modeling group",
        "Transportation Access and Mobility, Modeling",
        "atlantaregional.org",
    ),
    (
        "Chicago Metropolitan Agency for Planning (CMAP)",
        "IL",
        2,
        "",
        "Research and Programming, Modeling",
        "cmap.illinois.gov",
    ),
    (
        "Delaware Valley Regional Planning Commission (DVRPC)",
        "PA",
        2,
        "Philadelphia region; Office of Modeling and Analysis",
        "Office of Travel Modeling and Analysis",
        "dvrpc.org",
    ),
    (
        "New York Metropolitan Transportation Council (NYMTC)",
        "NY",
        2,
        "",
        "Technical Group, Modeling",
        "nymtc.org",
    ),
    (
        "National Capital Region TPB (MWCOG)",
        "DC",
        2,
        "Washington region; MATOC operations coordination",
        "Travel Forecasting and Analysis; Systems Performance",
        "mwcog.org",
    ),
    (
        "Boston Region MPO (CTPS)",
        "MA",
        2,
        "",
        "Travel Demand Modeling; Traffic Analysis",
        "bostonmpo.org",
    ),
    (
        "Southeast Michigan Council of Governments (SEMCOG)",
        "MI",
        2,
        "",
        "Plan and Policy Development, Modeling",
        "semcog.org",
    ),
    (
        "Metropolitan Council (Twin Cities)",
        "MN",
        2,
        "",
        "Metropolitan Transportation Services, Modeling",
        "metrocouncil.org",
    ),
    (
        "Denver Regional Council of Governments (DRCOG)",
        "CO",
        2,
        "",
        "Transportation Planning and Operations, Modeling",
        "drcog.org",
    ),
    (
        "Maricopa Association of Governments (MAG)",
        "AZ",
        1,
        "Phoenix; very active modeling and operations planning",
        "Transportation Technologies and Services; Modeling",
        "azmag.gov",
    ),
    ("Puget Sound Regional Council (PSRC)", "WA", 2, "", "Data and Modeling", "psrc.org"),
    ("Metro (Portland)", "OR", 2, "", "Research Center, Modeling", "oregonmetro.gov"),
    (
        "Mid-America Regional Council (MARC, Kansas City)",
        "MO",
        3,
        "Operation Green Light; bi-state",
        "Transportation and Environment, Modeling",
        "marc.org",
    ),
    (
        "East-West Gateway Council of Governments (St. Louis)",
        "MO",
        3,
        "",
        "Transportation Planning, Modeling",
        "ewgateway.org",
    ),
    (
        "Northeast Ohio Areawide Coordinating Agency (NOACA)",
        "OH",
        3,
        "",
        "Transportation Planning, Modeling",
        "noaca.org",
    ),
    (
        "Mid-Ohio Regional Planning Commission (MORPC)",
        "OH",
        3,
        "",
        "Transportation Systems and Funding; Modeling",
        "morpc.org",
    ),
    (
        "OKI Regional Council of Governments (Cincinnati)",
        "OH",
        3,
        "",
        "Transportation Planning, Modeling",
        "oki.org",
    ),
    (
        "Southwestern Pennsylvania Commission (SPC, Pittsburgh)",
        "PA",
        3,
        "",
        "Transportation Planning, Modeling",
        "spcregion.org",
    ),
    (
        "Baltimore Metropolitan Council (BMC)",
        "MD",
        3,
        "",
        "Transportation Planning, Modeling",
        "baltometro.org",
    ),
    ("Miami-Dade TPO", "FL", 2, "", "Planning, Modeling", "miamidadetpo.org"),
    ("Broward MPO", "FL", 3, "", "Systems Planning", "browardmpo.org"),
    (
        "MetroPlan Orlando",
        "FL",
        2,
        "I-4 corridor (historic VSL site)",
        "Transportation Planning, Modeling",
        "metroplanorlando.org",
    ),
    ("Hillsborough TPO (Tampa)", "FL", 3, "", "Planning and Modeling", "planhillsborough.org"),
    (
        "North Florida TPO (Jacksonville)",
        "FL",
        3,
        "Active ITS programme",
        "Planning; ITS",
        "northfloridatpo.com",
    ),
    (
        "Capitol Region Council of Governments (CRCOG, Hartford)",
        "CT",
        3,
        "",
        "Transportation Planning",
        "crcog.org",
    ),
    ("Hampton Roads TPO", "VA", 3, "", "Transportation Planning, Modeling", "hrtpo.org"),
    ("Richmond Regional TPO (PlanRVA)", "VA", 3, "", "Transportation Planning", "planrva.org"),
    ("Capital Area MPO (Raleigh)", "NC", 3, "", "Modeling", "campo-nc.us"),
    ("Charlotte Regional TPO", "NC", 3, "", "Transportation Planning, Modeling", "crtpo.org"),
    ("Wasatch Front Regional Council", "UT", 3, "", "Analytics and Modeling", "wfrc.org"),
    (
        "Pima Association of Governments (Tucson)",
        "AZ",
        3,
        "",
        "Transportation Planning, Modeling",
        "pagregion.com",
    ),
    ("Indianapolis MPO", "IN", 3, "", "Planning, Modeling", "indympo.org"),
    (
        "Regional Transportation Commission of Southern Nevada",
        "NV",
        3,
        "Runs FAST traffic management with NDOT",
        "FAST; Planning",
        "rtcsnv.com",
    ),
    ("Memphis MPO", "TN", 3, "", "Transportation Planning", "memphismpo.org"),
    ("Knoxville Regional TPO", "TN", 3, "", "Transportation Planning", "knoxtpo.org"),
    (
        "Chattanooga-Hamilton County/North Georgia TPO",
        "TN",
        3,
        "I-24 continues here",
        "Transportation Planning",
        "chcrpa.org",
    ),
]

CONSULTANCIES = [
    (
        "Gresham Smith",
        "TN",
        1,
        "Nashville-based; delivered the I-24 MOTION infrastructure; closest to the flagship",
        "Transportation / ITS practice lead; traffic modeling lead",
        "greshamsmith.com",
    ),
    (
        "Neel-Schaffer",
        "TN",
        1,
        "Nashville-region traffic engineering consultancy with TDOT work",
        "Traffic engineering practice lead",
        "neel-schaffer.com",
    ),
    (
        "Kimley-Horn",
        "US",
        1,
        "Very large traffic-engineering and microsimulation practice; publishes rate schedules",
        "National TSMO / traffic operations leads; regional simulation leads",
        "kimley-horn.com",
    ),
    (
        "Kittelson & Associates",
        "US",
        1,
        "Traffic operations and simulation specialists; HCM and calibration thought leadership",
        "Principals in traffic analysis and simulation",
        "kittelson.com",
    ),
    (
        "Fehr & Peers",
        "US",
        1,
        "Simulation-heavy planning consultancy on the West Coast",
        "Simulation and traffic operations leads",
        "fehrandpeers.com",
    ),
    (
        "DKS Associates",
        "US",
        1,
        "Traffic operations and ITS consultancy (West)",
        "Traffic operations principals",
        "dksassociates.com",
    ),
    (
        "Iteris",
        "US",
        1,
        "Consultancy plus software (ClearGuide); buys and sells traffic analytics",
        "Consulting services leads; product management",
        "iteris.com",
    ),
    (
        "Cambridge Systematics",
        "US",
        1,
        "Modeling and operations planning consultancy; TSMO programme work for DOTs",
        "Modeling practice leads",
        "camsys.com",
    ),
    (
        "HNTB",
        "US",
        2,
        "Large DOT consultant; publishes rate schedules; ITS and traffic practice",
        "Traffic engineering and ITS practice leads",
        "hntb.com",
    ),
    (
        "WSP USA",
        "US",
        2,
        "Large traffic and ITS practice; runs many DOT calibration studies",
        "Traffic and TSMO practice leads",
        "wsp.com",
    ),
    (
        "AECOM",
        "US",
        2,
        "Global; large simulation practice",
        "Traffic engineering and simulation leads",
        "aecom.com",
    ),
    ("Jacobs", "US", 2, "Large DOT consultant", "Traffic and ITS practice leads", "jacobs.com"),
    ("Stantec", "US", 2, "", "Transportation planning and traffic leads", "stantec.com"),
    ("HDR", "US", 2, "", "Traffic operations and ITS leads", "hdrinc.com"),
    ("Michael Baker International", "US", 2, "", "Traffic and ITS practice", "mbakerintl.com"),
    (
        "AtkinsRéalis",
        "US",
        2,
        "Simulation-heavy; UK roots in modeling",
        "Traffic modeling practice",
        "atkinsrealis.com",
    ),
    ("Arcadis", "US", 2, "", "Mobility and traffic practice", "arcadis.com"),
    (
        "Parsons",
        "US",
        2,
        "ITS systems integrator and TMC operator",
        "ITS practice; TMC operations",
        "parsons.com",
    ),
    ("Gannett Fleming (GFT)", "US", 3, "", "Traffic and ITS practice", "gftengineering.com"),
    ("STV", "US", 3, "", "Traffic engineering", "stvinc.com"),
    (
        "VHB",
        "US",
        2,
        "Northeast planning and traffic consultancy",
        "Traffic engineering and modeling",
        "vhb.com",
    ),
    ("Dewberry", "US", 3, "", "Traffic and ITS", "dewberry.com"),
    ("Burns & McDonnell", "US", 3, "", "Transportation, traffic and ITS", "burnsmcd.com"),
    ("CDM Smith", "US", 3, "", "Transportation planning and modeling", "cdmsmith.com"),
    ("KCI Technologies", "US", 3, "Mid-Atlantic traffic and ITS", "Traffic engineering", "kci.com"),
    ("RS&H", "US", 3, "Southeast DOT consultant", "Traffic and ITS", "rsandh.com"),
    ("Wade Trim", "US", 3, "", "Traffic engineering", "wadetrim.com"),
    ("Alfred Benesch & Company", "US", 3, "", "Traffic engineering", "benesch.com"),
    ("TranSystems", "US", 3, "", "Traffic and ITS", "transystems.com"),
    ("Mead & Hunt", "US", 3, "", "Traffic engineering", "meadhunt.com"),
    ("WSB", "US", 3, "Upper Midwest; MnDOT work", "Traffic and ITS", "wsbeng.com"),
    ("Sam Schwartz (TYLin)", "US", 3, "", "Traffic engineering", "samschwartz.com"),
    ("Steer", "US", 3, "Modeling consultancy", "Modeling practice", "steergroup.com"),
    (
        "RSG (Resource Systems Group)",
        "US",
        3,
        "Travel-demand modeling specialists",
        "Modeling practice",
        "rsginc.com",
    ),
    (
        "Southwest Research Institute (SwRI) ITS",
        "TX",
        2,
        "Builds ATMS software (Lonestar) for TxDOT and others; integration partner for a live path",
        "Intelligent Systems Division, ITS",
        "swri.org",
    ),
]

UNIVERSITIES = [
    (
        "Vanderbilt University, Institute for Software Integrated Systems",
        "TN",
        1,
        "Runs I-24 MOTION; co-led the 100-vehicle CIRCLES test",
        "Prof. Daniel B. Work (I-24 MOTION); Prof. Jonathan Sprinkle",
        "vanderbilt.edu",
    ),
    (
        "I-24 MOTION testbed",
        "TN",
        1,
        "The data instrument behind the flagship; the results are the introduction",
        "Data team (Derek Gloudemans et al.); testbed director",
        "i24motion.org",
    ),
    (
        "UC Berkeley, Institute of Transportation Studies / CIRCLES",
        "CA",
        1,
        "Led the CIRCLES consortium; RL traffic smoothing",
        "Prof. Alexandre M. Bayen; Prof. Maria Laura Delle Monache",
        "its.berkeley.edu",
    ),
    (
        "Temple University, Mathematics (CIRCLES)",
        "PA",
        2,
        "Traffic-flow theory; CIRCLES PI",
        "Prof. Benjamin Seibold",
        "temple.edu",
    ),
    (
        "Rutgers University–Camden (CIRCLES)",
        "NJ",
        2,
        "Traffic-flow theory; CIRCLES PI",
        "Prof. Benedetto Piccoli",
        "camden.rutgers.edu",
    ),
    (
        "University of Minnesota, Civil Engineering",
        "MN",
        1,
        "Lead author of the 2018 field experiments (FollowerStopper)",
        "Prof. Raphael Stern",
        "umn.edu",
    ),
    (
        "Texas A&M Transportation Institute (TTI)",
        "TX",
        1,
        "Largest US transportation research institute; TxDOT research arm",
        "Mobility and TSMO programme leads",
        "tti.tamu.edu",
    ),
    (
        "UT Austin, Center for Transportation Research (CTR)",
        "TX",
        2,
        "Texas modeling and network research",
        "CTR director; traffic modeling faculty",
        "ctr.utexas.edu",
    ),
    (
        "Georgia Tech, School of Civil and Environmental Engineering",
        "GA",
        2,
        "Traffic operations and CAV research",
        "Transportation systems faculty",
        "ce.gatech.edu",
    ),
    (
        "UC Irvine, Institute of Transportation Studies",
        "CA",
        2,
        "Traffic-flow theory and simulation",
        "ITS director; traffic-flow faculty",
        "its.uci.edu",
    ),
    (
        "Northwestern University Transportation Center",
        "IL",
        2,
        "",
        "Transportation center director",
        "transportation.northwestern.edu",
    ),
    ("MIT, Intelligent Transportation Systems Lab", "MA", 2, "", "ITS Lab faculty", "its.mit.edu"),
    (
        "Purdue University, JTRP",
        "IN",
        2,
        "INDOT research partnership; probe-data leadership",
        "JTRP director; traffic operations faculty",
        "engineering.purdue.edu/JTRP",
    ),
    (
        "University of Michigan, UMTRI / Mcity",
        "MI",
        2,
        "CAV testbed; OEM relationships",
        "Mcity director; UMTRI traffic faculty",
        "mcity.umich.edu",
    ),
    ("UCLA, Institute of Transportation Studies", "CA", 3, "", "ITS director", "its.ucla.edu"),
    (
        "University of Florida Transportation Institute (UFTI)",
        "FL",
        2,
        "FDOT research partner; simulation work",
        "UFTI director; traffic simulation faculty",
        "transportation.ufl.edu",
    ),
    (
        "Virginia Tech Transportation Institute (VTTI)",
        "VA",
        2,
        "Naturalistic driving data; CAV",
        "VTTI centre directors",
        "vtti.vt.edu",
    ),
    (
        "University of Maryland, CATT Lab",
        "MD",
        2,
        "RITIS probe-data platform used by many DOTs",
        "CATT Lab director",
        "cattlab.umd.edu",
    ),
    (
        "University of Wisconsin–Madison, TOPS Lab",
        "WI",
        3,
        "WisDOT operations research",
        "TOPS Lab director",
        "topslab.wisc.edu",
    ),
    (
        "Iowa State University, InTrans",
        "IA",
        3,
        "Iowa DOT research partner",
        "InTrans director",
        "intrans.iastate.edu",
    ),
    (
        "University of Tennessee, Center for Transportation Research",
        "TN",
        2,
        "In-state research partner for TDOT",
        "CTR director",
        "ctr.utk.edu",
    ),
    (
        "Penn State, Larson Transportation Institute",
        "PA",
        3,
        "",
        "Institute director",
        "larson.psu.edu",
    ),
    (
        "University of Washington, STAR Lab",
        "WA",
        3,
        "Smart transportation applications; WSDOT partner",
        "STAR Lab director",
        "uwstarlab.org",
    ),
    (
        "University of Central Florida, Civil Engineering",
        "FL",
        3,
        "Real-time crash risk and traffic safety modeling",
        "Traffic safety faculty",
        "ucf.edu",
    ),
    ("University of South Florida, CUTR", "FL", 3, "", "CUTR director", "cutr.usf.edu"),
    (
        "University of Toronto, Transportation Research Institute",
        "Canada",
        3,
        "International academic route",
        "UTTRI director",
        "uttri.utoronto.ca",
    ),
    (
        "TU Delft, Transport and Planning",
        "Netherlands",
        3,
        "Traffic-flow theory school (Hoogendoorn lineage)",
        "Traffic flow faculty",
        "tudelft.nl",
    ),
    (
        "TU Munich, Chair of Traffic Engineering and Control",
        "Germany",
        3,
        "SUMO-adjacent European research",
        "Chair",
        "tum.de",
    ),
]

FEDERAL_INDUSTRY = [
    (
        "FHWA Office of Operations",
        "US",
        1,
        "Owns the Traffic Analysis Toolbox guidance the report follows",
        "Office of Operations, Transportation Management; Traffic Analysis Tools programme",
        "ops.fhwa.dot.gov",
    ),
    (
        "FHWA Turner-Fairbank Highway Research Center (Saxton Lab)",
        "US",
        1,
        "CAV and traffic-operations research lab; testbed partnerships",
        "Saxton Transportation Operations Laboratory",
        "highways.dot.gov/research",
    ),
    (
        "USDOT ITS Joint Program Office",
        "US",
        2,
        "ITS research funding; deployment evaluation and cost databases",
        "ITS JPO programme managers",
        "its.dot.gov",
    ),
    (
        "TRB Traffic Flow Theory and Characteristics Committee (ACP50)",
        "US",
        1,
        "The academic community for this exact problem; Annual Meeting",
        "Committee chair; annual meeting sessions",
        "trb.org",
    ),
    (
        "TRB / NCHRP",
        "US",
        2,
        "Research problem statements; synthesis projects",
        "NCHRP programme officers",
        "trb.org/NCHRP",
    ),
    (
        "Institute of Transportation Engineers (ITE)",
        "US",
        1,
        "Practitioner community; section meetings are the consultant channel",
        "ITE sections (Tennessee, Texas, Florida); TSMO council",
        "ite.org",
    ),
    (
        "ITS America",
        "US",
        2,
        "Industry association; annual conference",
        "Membership and programme staff",
        "itsa.org",
    ),
    (
        "AASHTO Committee on Transportation System Operations",
        "US",
        2,
        "State DOT operations leaders in one room",
        "Committee liaison",
        "transportation.org",
    ),
    (
        "Association of Metropolitan Planning Organizations (AMPO)",
        "US",
        2,
        "400+ MPOs; annual conference and modeling working groups",
        "AMPO staff; Travel Modeling working group",
        "ampo.org",
    ),
    ("Traffic Engineering Council / ITE TSMO Council", "US", 3, "", "Council chairs", "ite.org"),
    (
        "USDOT SBIR / STTR programme",
        "US",
        2,
        "Federal small-business research funding path",
        "Volpe Center SBIR office",
        "volpe.dot.gov/sbir",
    ),
    (
        "National Operations Center of Excellence (NOCoE)",
        "US",
        2,
        "TSMO practitioner network run by AASHTO, ITE and ITS America",
        "NOCoE staff; TSMO awards",
        "transportationops.org",
    ),
]

FLEETS_OEMS = [
    (
        "Nissan North America (Franklin, TN)",
        "TN",
        1,
        "CIRCLES field-test partner; headquartered next to the I-24 corridor",
        "Advanced vehicle engineering; research partnerships",
        "nissanusa.com",
    ),
    (
        "Toyota Motor North America R&D / Toyota Research Institute",
        "US",
        1,
        "CIRCLES partner; traffic-smoothing research interest",
        "TRI research; TMNA R&D",
        "tri.global",
    ),
    (
        "General Motors",
        "US",
        2,
        "Super Cruise fleet; traffic-flow research",
        "Advanced engineering; ADAS",
        "gm.com",
    ),
    (
        "Ford Motor Company",
        "US",
        2,
        "BlueCruise fleet",
        "Research and advanced engineering",
        "ford.com",
    ),
    (
        "Waymo",
        "US",
        2,
        "Largest robotaxi fleet; interested in traffic-flow effects",
        "Research; policy and public affairs",
        "waymo.com",
    ),
    (
        "Aurora Innovation",
        "US",
        2,
        "Autonomous trucking on Texas freeways (I-45)",
        "Autonomy research; policy",
        "aurora.tech",
    ),
    (
        "Kodiak Robotics",
        "US",
        3,
        "Autonomous trucking on Texas corridors",
        "Autonomy; partnerships",
        "kodiak.ai",
    ),
    ("Zoox", "US", 3, "", "Research", "zoox.com"),
    ("May Mobility", "US", 3, "", "Partnerships", "maymobility.com"),
    ("Motional", "US", 3, "", "Research", "motional.com"),
    ("Torc Robotics", "US", 3, "Autonomous trucking (Daimler)", "Autonomy research", "torc.ai"),
    (
        "Tesla (Autopilot / FSD)",
        "US",
        3,
        "Largest driver-assistance fleet; long shot",
        "Autopilot engineering",
        "tesla.com",
    ),
]

DATA_VENDORS = [
    (
        "Caltrans PeMS",
        "CA",
        1,
        "Public detector data; loader exists; the DOT-style validation case",
        "PeMS programme (Caltrans Division of Traffic Operations)",
        "pems.dot.ca.gov",
    ),
    (
        "INRIX",
        "US",
        2,
        "Probe speed data sold to DOTs; a live-path data channel",
        "Public sector partnerships",
        "inrix.com",
    ),
    (
        "HERE Technologies",
        "US",
        2,
        "Probe data; DOT contracts",
        "Public sector; automotive",
        "here.com",
    ),
    (
        "StreetLight Data",
        "US",
        3,
        "Location-derived demand data (counts alternative)",
        "Public sector sales",
        "streetlightdata.com",
    ),
    (
        "Wavetronix",
        "US",
        2,
        "Radar detectors on most freeways; the sensor for a live path",
        "OEM / integrator partnerships",
        "wavetronix.com",
    ),
    ("Teledyne FLIR ITS", "US", 3, "Thermal traffic sensors", "ITS partnerships", "flir.com"),
    (
        "Rekor Systems",
        "US",
        3,
        "Roadway intelligence platform for agencies",
        "Partnerships",
        "rekor.ai",
    ),
    (
        "Miovision",
        "Canada",
        3,
        "Traffic data and signal analytics",
        "Partnerships",
        "miovision.com",
    ),
    (
        "Econolite",
        "US",
        3,
        "ATMS and controllers; integration partner",
        "Product management",
        "econolite.com",
    ),
    ("Q-Free", "US", 3, "ATMS (Kinetic) integrator", "Partnerships", "q-free.com"),
    ("Kapsch TrafficCom", "US", 3, "Managed lanes and ATM systems", "Partnerships", "kapsch.net"),
    (
        "Cubic Transportation Systems (ITS)",
        "US",
        3,
        "ATMS integrator (GRIDSMART lineage)",
        "Partnerships",
        "cubic.com",
    ),
    (
        "TDOT SmartWay Traffic Management Center",
        "TN",
        1,
        "Operates the I-24 SMART Corridor gantries; the live path's first actuator",
        "TMC operations manager",
        "smartway.tn.gov",
    ),
    (
        "PTV Group",
        "Germany",
        3,
        "Incumbent simulator; possible integration or channel, also a competitor",
        "Partnerships",
        "ptvgroup.com",
    ),
    (
        "Aimsun",
        "Spain",
        3,
        "Incumbent simulator with real-time products; competitor and reference",
        "Partnerships",
        "aimsun.com",
    ),
    (
        "Caliper Corporation (TransModeler)",
        "US",
        3,
        "Incumbent simulator",
        "Partnerships",
        "caliper.com",
    ),
]

GROUPS = [
    ("State DOT", STATE_DOTS),
    ("MPO / regional agency", MPOS),
    ("Consultancy", CONSULTANCIES),
    ("University / research lab", UNIVERSITIES),
    ("Federal / industry body", FEDERAL_INDUSTRY),
    ("AV fleet / OEM", FLEETS_OEMS),
    ("Data, sensors, integrators", DATA_VENDORS),
]

PITCH_BY_TYPE = {
    "State DOT": "A calibrated twin of one of your corridors from public map data and your detector data, with the calibration report your reviewers expect, in a day of machine time; pilot priced as a study.",
    "MPO / regional agency": "Corridor-level operations analysis that plugs into your regional model outputs; smoothing, VSL and metering scenarios with confidence intervals.",
    "Consultancy": "The two weeks of hand calibration per corridor, automated: onboard from OpenStreetMap, calibrate to counts, run scenarios, generate the report. Per-study pricing first.",
    "University / research lab": "An open engine and a published validation record on I-24 MOTION data; collaboration on the merge and controller work; free or near-free licence.",
    "Federal / industry body": "A reproducible, open validation record that follows the Traffic Analysis Toolbox; a speaker or demo for a session; SBIR fit.",
    "AV fleet / OEM": "Before deploying smoothing at scale, the dose-response on a calibrated real corridor: what 1 to 20 percent penetration does to throughput, travel time and fuel.",
    "Data, sensors, integrators": "The live-advisory path needs sensing and actuation partners; FlowState brings the calibrated model and the state estimator.",
}

HEADERS = [
    "Organisation",
    "Type",
    "Region",
    "Priority (1 = first)",
    "Why they matter",
    "Role or person to reach",
    "Named public contact (papers / programme leads only)",
    "Website",
    "Channel",
    "Pitch angle",
    "Email",
    "Status",
    "Notes",
]


def rows() -> list[list[str]]:
    out: list[list[str]] = []
    for type_, items in GROUPS:
        for org, region, prio, why, role, web in items:
            named = ""
            if type_ == "University / research lab" and "Prof." in role:
                named = role
                role = "Faculty listed; also the lab's programme manager"
            channel = "Public contact page on the website; LinkedIn for the named role; TRB Annual Meeting and ITE section meetings"
            if type_ == "State DOT":
                channel = "Agency directory (traffic operations / TSMO division); ITE state section; AASHTO CTSO"
            elif type_ == "University / research lab":
                channel = "University directory (public academic e-mail); cite the FlowState I-24 results in the first line"
            elif type_ == "AV fleet / OEM":
                channel = (
                    "Research partnerships page; warm introduction through CIRCLES or Vanderbilt"
                )
            out.append(
                [
                    org,
                    type_,
                    region,
                    str(prio),
                    why,
                    role,
                    named,
                    "https://" + web,
                    channel,
                    PITCH_BY_TYPE[type_],
                    "",
                    "not contacted",
                    "",
                ]
            )
    return out


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    data = rows()
    data.sort(key=lambda r: (int(r[3]), r[1], r[0]))
    csv_path = OUT_DIR / "outreach_targets.csv"
    with csv_path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(HEADERS)
        w.writerows(data)
    wb = Workbook()
    ws = wb.active
    ws.title = "Targets"
    ws.append(HEADERS)
    for r in data:
        ws.append(r)
    head_fill = PatternFill("solid", fgColor="123B6D")
    for c in ws[1]:
        c.font = Font(bold=True, color="FFFFFF")
        c.fill = head_fill
        c.alignment = Alignment(vertical="center", wrap_text=True)
    widths = [44, 22, 10, 10, 60, 44, 40, 36, 52, 70, 26, 14, 30]
    for i, wdt in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = wdt
    for row in ws.iter_rows(min_row=2):
        for c in row:
            c.alignment = Alignment(vertical="top", wrap_text=True)
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions
    how = wb.create_sheet("How to use")
    lines = [
        "FlowState outreach targets (generated by scripts/business_outreach_list.py)",
        "",
        f"{len(data)} organisations across {len(GROUPS)} segments, sorted by priority, then type.",
        "Priority 1 = talk to first: they own the flagship corridor's data, do the calibration work the product replaces, or fund the research route.",
        "",
        "No personal e-mail addresses are included on purpose. The 'Role or person to reach' column names the job title; find the current holder in the agency directory or on LinkedIn, and use the organisation's public contact page or the named academic's university e-mail.",
        "Named people appear only where they are public authors of the cited papers or programme leads (I-24 MOTION, CIRCLES, the 2018 field experiments).",
        "",
        "Suggested sequence (docs/INTERVIEWS.md has the 30-minute script and the outreach template):",
        "  1. Priority-1 consultancies and the Nashville-region agencies (warm paths: I-24 MOTION data team, TDOT research office).",
        "  2. Priority-1 university labs, with the I-24 results attached; ask for a collaboration and an introduction.",
        "  3. State DOT TSMO divisions in Texas, California, Florida and Georgia; then the MPOs in the same regions.",
        "  4. OEMs and fleets only after one agency pilot is under way.",
        "",
        "Track the 'Status' column: not contacted, e-mailed, replied, call booked, interviewed, pilot discussion, declined.",
        "Never send an outreach e-mail unread; adapt the template in docs/INTERVIEWS.md section 4.",
    ]
    for ln in lines:
        how.append([ln])
    how.column_dimensions["A"].width = 140
    xlsx_path = OUT_DIR / "outreach_targets.xlsx"
    wb.save(xlsx_path)
    counts = {}
    for r in data:
        counts[r[1]] = counts.get(r[1], 0) + 1
    print(f"-> {xlsx_path} and {csv_path}: {len(data)} organisations", counts)


if __name__ == "__main__":
    main()
